### ISSUE TITLE
Can't Change dimensions of PDF

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#100]
http://s64705085-preview.tizrapublisher.com/erisa-outline-book-chapter-3a/4

For some reason I can not adjust the width of the PDF on the ASPPA site using the "Page Content" block in tizra. Can you please look into this and let me know how to fix this?

**Comment by daviddurand** [comment]
I'm going to need a bit more detail to understand your problem, I'm afraid. There are a couple of tricky things around page dimensions that could be problems for you, and I've put them here in case they are the answer to your questions (and because I think they may make a good wiki page sometime):
- In PDF mode, Safari and Chrome use their own PDF plugins that do not implement several features of Adobe's plugin, so that they decide how big the page will be inside the rectangle, and will fill extra space with white, or add scrollbars, depending on how that size relates to the dimensions you set on the rectangle. I have tried every way I can to change the presented size, or to figure out a conversion factor that will make things look good, and have failed. It does not even seem 100% consistent between PDFs, but I have not been able to find out what affects it.
- the block sizes in the content block may work a bit differently in different viewers (e.g. in the ipad, because of the zoom, a document fits to the width of the screen). For image mode display, it defines a desired size, but the actual must be sized to fit within the rectangle given because it may be a different shape than the block specifies. Also, if the image is too large, reduced resolution is given because there are practicality limits in the size of single images in a browser and on the server.
- Consequently, if you really want to hard-wire a size you can use a CSS override on the image tag (and unfortunately take the risk of distortion because the aspect ratio may be different). The markup strategy I am moving to in the reader is based on sizing the div around the image and using a width of 100% and unconstrained height to ensure that the image is not distorted and fills the right area. (You might switch height and width in that recipe if you have pages wider than they are tall, or want to avoid scrolling). There will almost certainly be more of this in the new reader, but the zoom user experience for the reader will make this kind of sizing irrelevant.
- if you have a zoomFactor specified in the URL for a page, that will affect the size, but there are a number of restrictions in how that is processed (it was originally only for internal purposes,  but we have documented its use to produce reduced size pages for use with the sampling feature).

**Comment by ghost** [comment]
What is happening isn't a browser issue, and I know I can impact the size with css, but your system doesn't appear to be doing what it should. So, I created a video: http://screencast.com/t/YmIOB41vEc.

In the video, I jump the width of the PDF up by 200 (px? not labeled in your system) then go back to the staging site and refresh. Nothing changes. I do not have any css controlling the width on the staging server, or I can't find it if I do. 

I was able to drop the size down, but it refuses to go over 686px wide. 

As a side note, although chrome uses their own plugins, you can force acrobat to be the pdf plugin that is used. I think the same can be done with safari, but I have only tested on a mac.

**Comment by daviddurand** [comment]
OK, I wrote something complicated, but in that process, I missed writing the first thing that popped into my head on reading your question:
- Image block parameters are actually **maximums** 
  All the fitting and approximating and scaling stuff that I wrote above is also true, but it is limited by the zoomFactor and the original page size. So the answer is still the same as described in the third bullet point -- if you need to fix the size, you need to use CSS, because the system starts with a zoom factor of 1.0 which means 72 pixels per graphical inch in the PDF.

It's at least arguable that CSS is the best way to resize things in modern site designs anyway.

I can imagine a lot of controls that we could add to the page block to adjust this better or at least differently, but the whole sizing process is undergoing radical change at this time (as we move away from PDF plugins), and any changes will be driven by the needs of the new reader.

[as an aside, forcing adobe's plugin solves nothing because most users don't want to install it, and it is unavailable for most browsers on the mac. If it does work for Chrome, that is a recent event of the last few months at the longest.]

I'd also like to remind you that this is a _product_. We're always interested in hearing suggestions, and I'm often willing to spend a little time talking about pros and cons, but _if_ there is a workaround (or more than one), _that's what you have_ until such time as **we** (Tizra) _may_ decide to change the way the product works. Unless you are willing to pay for a custom feature, and we agree that the change makes sense. I spend time to try to explain some some of these decisions, but unless really significant new information or arguments surface, they are still decisions, not points for debate.

**Comment by ghost** [comment]
I'm not trying to debate you on anything. I'm making changes to an editable block in your system, and it does nothing. It seemed like a bug, so I reported it. I'll fix everything with css.
