### ISSUE TITLE
Can't extract zip file of Static Export

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#101]
To reproduce go to omniplayground.tizrapublisher.com/admin/main and export the design that is in staging called "000000EXPORT" then extract the files to your computer. I don't get an error but I also don't get any files.

I've tried this on a few different machines and haven't been able to get the files extracted. This started happenning between 1:40 and 2:55

Thanks

**Comment by daviddurand** [comment]
I spent time Friday on this, and will look further this weekend. It's something to do with the design parameters on your site, particularly the IE6-related image file. My dgd `dgd test` designs have some variations, but you can see that `000000EXPORT ie6 removed` does export properly. Just removing the graphic did not fix everything, you have to remove the property. I was able to find the property in question because the command-line unzipper can recover from the file problem and tells you what file did not compress properly -- I was then able to search the source for that file number and find the associated parameter.

This is not an acceptable workaround, obviously, but should let you make some progress in testing the markup while I investigate the problem further.

Update: I've now determined that the problem specifically comes from the particular image file stored in the IE parameter. There must be an underlying bug, but I'm now clearer as to why this was hard to detect and replicate, and also what might be going on.

**Comment by daviddurand** [comment]
At this point I've fixed the original layout, and failed to replicate the problem on any other machines (with the same file, parameter names, etc). Design parameters have a new MIME-type feature that grew out of the debugging now, which is not a bad thing.

At this point I'm going to leave this, in the hope that you can proceed with one of the replacement designs, until we can see if the error recurs, and maybe then we can gather some more information on it. If you replace that jpg with the version that I used on the repaired design, that should do it.

**Comment by daviddurand** [comment]
I'm closing this until if and when we get a replication of the problem.

**Comment by orangedrink** [comment]
OK. Working fine atm
