### ISSUE TITLE
Problem with titles of virtual collections

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#105]
On the WEFTec  site i'm going to be using virtual collections. I created one with the title "test ${item.props.time}"

But the title throws an error:
http://s83016494-preview.tizrapublisher.com/test@time=11:00

It's possible that I'm doing something wrong here. Let me know.

By the way am I correct in assuming that there is no "virtual collection list block" that will list all of the virtual collections built around a certain property? I'm planning to try using JSON to generate my own but don't want't to reinvent the wheel if you already have one rolling around.

Thanks!

**Comment by daviddurand** [comment]
The variables you use for virtual Collections are ${this.props.whatever}  ${item} is used with offers, and refers to the object to which the offer is attached (which might be an individual object or a collection).

${this} is also available in the new special template of the list block, which enables things like this:

`<a href="/${this.urlId}"><img src="${this.urlId}/1.jpg?zoomFactor=.1" /></a>`

In the case of an offer on the items of a collection, the value of item will be the particular item within the collection that a user is attempting to work with at the time it is displayed. So the same offer can be in the cart multiple times, each time applied to a different item for purchase.

The Virtual collection list block you describe does not exist, but is something that we intend to create. I don't think you can get all the information you need from the JSon interface at this point. We should chat about this on the phone at some point, as  the power that this will allow needs a little care in application, since Virtual Collections can create many many items very quickly -- as they combine multiplicatively.

**Comment by orangedrink** [comment]
Is it possible to use this to show a property that has characters that are not legal inside a url? For example ofn the WEF site I would like to show the sessionTitle property at the top of each VC but many of these have slashes or question marks so a link like `http://weftec2012.tizrapublisher.com/ses@sessionTitle=Leading%20Practices%20and%20Tools%20for%20Taking%20an%20Integrated%20Approach%20to%20Stormwater%20and%20Floodplain%20Management%20for%20Healthy%20and%20Impaired%20Watersheds/` isn't going to work

I am able to link to these VCs using a link like `http://weftec2012.tizrapublisher.com/ses@sessionNumber=0` since the sessionNumber property corresponds to a sessionTitle but then I'm not able to use `${this.props.sessionTitle}` to show the title of that session within the VC.

Let me know if there is a workaround for this. If you can help me in making this work I'd be glad to share my all javascript VC list block: http://weftec2012.tizrapublisher.com/2gj6rg// 

Thanks!

**Comment by orangedrink** [comment]
Let me know if it isn't clear what I'm getting at here.

**Comment by daviddurand** [comment]
The ${} macros use the freemarker macro language. Doc is at http://freemarker.org/  and the section you want is http://freemarker.org/docs/ref_builtins_string.html#ref_builtin_url

So `${this.props.sessionTitle?url}` should do what you want.

**Comment by orangedrink** [comment]
It's still throwing an error
http://weftec2012.tizrapublisher.com/ses@sessionTitle=Inspecting%20and%20Optimizing%20Pump%20Stations%20and%20Forcemains

Now on pages that have illegal characters in the sessionTitle I get a blank page
http://weftec2012.tizrapublisher.com/ses@sessionTitle=Highlights%20from%20ISA's%202012%20Water%2FWastewater%20and%20Automatic%20Controls%20Symposium

**Comment by daviddurand** [comment]
OK, I'm wasn't seeing any error on these pages because the collections were not populated any more, and so the URL was going to the home page.

I do see an error in the admin interface, and that's something that should not happen, so I will work on that.

I added a test document with time=11:00, and that page seems to be displaying OK.

http://s83016494-preview.tizrapublisher.com/test@time=11:00

I saw the error with the spaces, with my test url:

http://weftec2012.tizrapublisher.com/ses@sessionTitle=test%20space

**Comment by daviddurand** [comment]
OK, Actually there is not a problem.

the ?url was something for you to use _in markup_ if you were constructing a URL by hand. Putting it in the title itself created a different problem.

You will notice that I added in the string !'unknown' to the variable substitution -- if you don't do that, you will get an error when displaying virtual collection instances that don't have a value for that particular variable -- and also if you try to visit the base URL (which is the Virtual Collection Definition).

By the way, when you visit a Virtual collection that is only partially specified, you will get all members of the virtual collection that match that property, and that have non-blank values defined for the other properties in the collection. That means that Virtual collection definition itself, say:

http://weftec2012.tizrapublisher.com/ses

May be a quite large collection, because it will include all the items that would be part of any of its child collections.

By the way, when you are testing VCs you may create a bunch of collection instances that you don't want to keep, and that will be empty anyway, so you may want to delete those from the instances list in the VC admin area.

The template errors in the admin area are, I think, actually a good thing, as they provide immediate feedback as to any variable substitution problems in your metadata fields.

If you look at the current test document, I think you can see that it's all actually working, including spaces.

**Comment by orangedrink** [comment]
Spaces aren't the problem. Look at these links

http://weftec2012.tizrapublisher.com/ses@sessionTitle=Highlights%20from%20ISA's%202012%20Water%2FWastewater%20and%20Automatic%20Controls%20Symposium

http://weftec2012.tizrapublisher.com/ses@sessionTitle=Leading%20Practices%20and%20Tools%20for%20Taking%20an%20Integrated%20Approach%20to%20Stormwater%20and%20Floodplain%20Management%20for%20Healthy%20and%20Impaired%20Watersheds

http://weftec2012.tizrapublisher.com/ses@sessionTitle=Establishing%20Water%20Rights%20for%20Water%20Reuse%20and%20Recycling%3A%20How%20To%20Manage%20Your%20Existing%20Recycled%20Water%20Resources%20and%20Plan%20Future%20Recycled%20Water%20Projects

**Comment by daviddurand** [comment]
The current VC definition is probably not what you want: you have a nested collection defined on SessionNumber and SessionTitle. The collection instances were a mess, including a session called `*` which might definitely create some problems for search indexing. I deleted the old inconsistent instances. Unless you want a virtual collection that is defined to created nesting collections on SessionTitle _and_ SessionNumber, pick one, use that consistently, and delete any instances referring to the other property so that you can tell what is going on as the collections are created on access.

I think the problem is URL characters in the values, as I said above. So the URLs that are not working include `:` `/` and other things like that. Escaping them doesn't help, unfortunately. Virtual collections were really designed for simple keys. I did not enforce a lot of restrictions, so that we could experiment with things like author-based collections, but using titles really isn't part of design and testing. I can look into changing the URL escaping strategy, but it can't be a high priority item right now. Also, a consistent escaping strategy will almost certainly involve double-escaping so `%3A` would have to appear as `%253A` -- unescaped once so that the URL can be parsed,  `%253A` will become `%3A` which can then be unescaped to `:`. This will be hard to manage, and the URLs will be very ugly, so again, it argues against using the title. Basically, arbitrary strings are hard to handle in a URL, and even harder if they need to be escaped just for a portion of a URL.

It will be much faster to use the supertagger to change the values for the virtual collections than to wait for us to try to handle these cases, especially since the resulting URLs will really not be very good practice.

**Comment by orangedrink** [comment]
Thank you David.

If we can't display textual data as the titles of the virtual collections than the usefulness of virtual collections are pretty limited. I feel like this is a restriction we should have been made aware of before we were planned to use them on a job that needs to proof today.

**Comment by orangedrink** [comment]
Can we at least get a list of characters that are not allowed?

**Comment by daviddurand** [comment]
It's the characters that are not allowed in URLs without escaping. So, by definition they are also the characters that will not be recognizable to users when they are in a URL (and %-encoded). I believe the critical ones for Tizra are: `:/?;`. The official list (of characters that you would not expect a web based system to handle are in [RFC3986](http://tools.ietf.org/html/rfc3986#section-2.2):

```
:/?#[]@
!$&'()
*+,;=
```

It's really worth poring over the RFCs at least a few times.You will note that I use the "gen-delim" character `@` in VC URLs -- based on actual practice on the web -- as well as the details of the http: URL scheme, and the escaping rules, which mean that I can assume that unescaped `@` is not part of a filename or something.

Dividing a URL at occurrences of `/` and `:` is one of the first steps in processing a URL. Those are the two characters that I know are causing problems. I think you can get away some of the others as we don't deal with them, but I expect that `;` may cause trouble, as it's used internally by Tizra in putting list-valued properties into the search engine. And the first `?` in a URL is used to split the URL in two even before the paths are parsed. `*` is going to cause troubles with Lucene, and for security reasons (denial of service attacks), I'm probably going to have to filter it out at some point.

I'm sorry you got stuck, but URL syntax is a fact of the web, and I've tried to warn against "exotic" URLs in the past.

If you really thing your users want 100+ character URLS, you should make a filtered form of the Title with spaces changed to dashes or underscores, and special characters deleted, and then use that -- it would not _literally_ be the Title metadata property, but it would be exactly those parts of the Title that can be put into a URL in a way that an end-user can read.

Here are a few things I found in a few minutes of email searching....

From my first email describing virtual collections (Feb 8 2011):

```
You should not try to make VCs with properties that have "list" values like "Keywords". Values like numbers, true/false, work well. Single keyword is the best. I will probably add multiple keywords fields but there are a few issues that I have to figure out first.
```

At a later date, I added list values for VC member properties.

In reply to a question about using various other properties in virtual collections (March 14 2011):

```
A VC by author would probably work, but how many papers does an author really have?
Would those collections really be useful?
```

I think that _"Would probably work"_ is the key phrase here, though it does include an invitation for you to experiment if you want. Titles are obviously even more problematic than author names.

In general I've discouraged weird characters in URLs, as for instance on (Oct 25, 2010):

```
I noticed that you are using Custom URLs, which is good, but it's
better to avoid spaces in URLs -- it can create problems for people
(and besides all the %20 replacements look ugly).
```

**Comment by orangedrink** [comment]
None of this makes it clear that certain characters are not allowed. In your March 14th mail you are DEFINITELY proposing that we build virtual collections around author names because you didn't want to change how search results were ordered.

These urls are all encoded as recommended by the RFC. It's an internal tizra problem. Not a "Fact of the web" or 
periods wouldn't be causing a problem. 

Please let me know what other parts of the system "will probably work" so we can plan to avoid using those as well.

**Comment by daviddurand** [comment]
Tizra URLs can enforce any restrictions on format they want. Tizra is a product, and the Tizra system defines what URLs are legal for Tizra documents. Most CMS's enforce a lot more restrictions than we do. Yes, I have implemented URL-encoding for one important case.

In the past, I have consistently advised use of conservative URLs character sets, and the user and reliability advantages of avoiding URL-encoding. If your intuition when planning this site did not suggest that certain special characters might be a problem, the RFC is offered to clarify the things that you should watch out for in the future -- because use of those characters in a URL on any server requires special code support.

I often attempt to collaborate with you to find ways to push the system to solve special problems -- sometimes I can even make a quick adjustment to make your life easier -- if suggesting that you try something unusual is going to be taken as a blanket assertion that anything goes for that feature, I can stop doing that, and you can accept the additional limitations of living the the "totally safe" zone.

So, **to be totally clear** what I meant is:
- **"No, that is not a bug, it is a system limitation"**
- **"Now you know how the system works."** 
- **There are two ways to do what you want:** You can use session identifier keywords. Or you could make a new `URLSessionTitle` field, just as you make special sort fields.

In the discussion a few other facts came up:
- "We did not explicitly forbid arbitrary field values in VC URLs." However, the documentation on Virtual Collections _explicitly_ recommended sticking to keywords and simple values. With a system this powerful, we can't make exhaustive lists of all the things we don't recommend and why they might not work. If you go beyond the documented use of a feature, you need to have time and a plan in case it does not work as you expect. Don't be spoiled by the fact that often Tizra features can be applied in surprising ways.
- **"If you want to experiment with special characters in Virtual Collection URLs, knock yourself out."** You now know that Tizra does not implement double URL-encoding. Even so, some of the characters in the RFC list probably do work, and you are free to test them, if you have a need.
- There was a change about two years ago in which we started to support arbitrary characters in the custom URL for a publication, but at the moment _that is the only place that characters requiring URL-encoding_ are a fully-supported part of a Tizra object name. (URL-encoding is also used as part of the login protocol, SSO, etc. but these are very different cases in programmer-only interfaces).

**Comment by orangedrink** [comment]
Because of how our jobs are scheduled we do usually need to live in the "Totally Safe Zone". I just need to know what is in this zone and what isn't. If you can't tell me what does and doesn't work with your system how are we supposed to plan and build sites with it? 

Please send me the documentation on using VCs and on anything else you have that might prevent us from making promises your system can't deliver on. From now on if a feature isn't explicitly documented I won't assume that your system can do it.

**Comment by daviddurand** [comment]
I have a fix ready to go on this, and it should go live tomorrow. I'm going to be testing locally today as there is always a little extra risk in changing something as fundamental as URL processing.

I discovered that I had not handled certain characters (like '/' and '?') in display URLs either. The new fix should allow URL-escaped characters of any kind pretty much anywhere in Tizra URLs. I'm going to do some international character tests now...

**Comment by daviddurand** [comment]
fix is in place... Please check as this is a complicated case -- or at least one that involves potentially subtle interactions.
