### ISSUE TITLE
Static Export: Need a way to remove tags for author index without removing author index from live site

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#109]
Since we are now adding the link to the AI manually to the static export rather than having our existing author indices exported we need a way to remove the existing AI from the static export without removing it from the live site.

For example I have a site with an Author index that was created using a static page. This Static page is tagged as 'nav' so that it appears in our top navigation.

In order to create the static export with an author index I need to add the link manually to the main nav masterblock and remove the nav link from the existing author index static page. I'm not currently able to remove this tag from the static export only without also publishing the static page to live and having the AI disappear from the live site. 

Let me know if you have any questions.

**Comment by daviddurand** [comment]
If you just use the normal index macros and not the special static page, you won't need to have these variants. In the mean time, you will probably have to have a variant of the design for static export. You might be able to make this somewhat painless by creating design properties for the key items that have to change between the two designs, so that you quickly "make a design static" by changing a couple of these fields to create the alternate design.

However, I will add macro support that you can use for conditional markup in static sites to control the appearance of content based on the export state.

Also, it occurs to me to warn you that the recent addition of freemarker macros (`${}` and it's friends) in more areas of the design tools interface is not currently supported in the static export which is designed for simpler sites.

**Comment by daviddurand** [comment]
Just looking at this again. 

One thing  seems to be worth revisiting:

> In order to create the static export with an author index I need to add the link manually to the main nav masterblock and remove the nav link from the existing author index static page. I'm not currently able to remove this tag from the static export only without also publishing the static page to live and having the AI disappear from the live site.

I think you can do all of this automatically. Make a new tag `staticNav`, and just change the masterblock used for the static export to use the tag `staticNav` rather than `nav`. Every page but the author index will have the `nav` and `staticNav` tags, except for the two author indexes, one of which will be marked `nav` and will be linked on the live design, and the other will be tagged `staticNav` and will be linked in the static export. You will have a published static AI page on the site, but it should not be an issue, because it won't be linked.

Does this help? I know you'd love to have **no** differences between that export and live templates for a site, but that is something that has always presented some problems -- some of them very different from what we thought at the beginning.

In #132 you mention a bug in property display. How important to your sites would these manual overrides be if that bug were fixed?

**Comment by orangedrink** [comment]
That does help. It's enough work that we would probably only do this if the customer was very sensitive but good to have that option.

If you were able to fix the bug described in 132 we could definitely stop using these manual overrides on most sites and probably on all sites that have a static export. That would definitely be helpful.

Thanks!
