### ISSUE TITLE
PDF Page Full Screen Bug

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#115]
http://abaseer20fm.conferencespot.org/01-Plenary/1

If you go to the above page, and click the full screen icon (fourth from top), then click "fit to page" horizontally and then exit full screen, the PDF doesn't resize to fit the original viewer.

**Comment by daviddurand** [comment]
This was the result of fixing some preference saving bugs.
It is fixed now.

**Comment by ghost** [comment]
It seems as if your recent update also fixes the issue from https://github.com/Tizra/Tizra-Customer-Tracker/issues/100 

Am I accurate with saying this? If so, I'm going to remove any css that I put in to view things correctly.
Thanks.

**Comment by daviddurand** [comment]
I don't think so, because a maximum size is a maximum. I got something wrong in that earlier response in that the effective pixel density for Tizra is 95 PPI, and not 72 PPI. (Real inches will depend on the screen, of course.) So what happens if you have a smaller than usual page is that you get a smaller than usual image.

One thing that is different (and may be good for you), is that I now include an actual image size on the image tags -- this speeds rendering, and prevents some of the size anomalies you may have been guarding against. I need to float that image in its containing div (so that the container will be sized based on the size of its contents and not on the size of its parent). That doesn't cause any weirdness because nothing else shows up in that div.

For Tizra layouts, because the content may vary in size, I still recommend dynamic layouts, but as long as the source material is consistent in format, you could fix things.

The new reader has come a long way -- tomorrow it will support hyperlinks even in image mode, for example. And PDF mode is now gone as an explicit option.

You guys may want to have some links to the pdf format of pages for browsing posters, but the PDF plugin is soon going to be gone except for such special cases I hope, leading to more predictable world...
