### ISSUE TITLE
User upload as it applies to SDE and status 99

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#119]
First I would like to say that this user uploader seems to be pretty versatile. I love it.

I do have a question about removing user tags as they apply to SDE. You probably remember that when SDE has a user with a status code of 99 it means that any tags in this line of the upload file need to be removed. I'm using the import definition below and it's very close: 

UserData  
Status  RegistrationCode    MeetingCode     PersonId    FirstName   LastName    EmailAddress    SessionNoSpace
keep    keyword             keyword-list    string  string  string  string          keyword-list
------- ------------            add-user-tags   id          ---------   --------    -------                 spaced-list when:Status!99:add-user-tags MeetingCode/SessionNoSpace when:Status=99:delete-tag-prefix=MeetingCode

On a line with status of 99 It removes all of the tags that begin with the current status code but not the status code itself. For example a user with tags that look like "C123; C123/A1; C123/A2" is uploaded with a status of 99, a MeetingCode of "C123" and SessionNoSpace as "A1 A2" the user winds up still having the tag of "C123" since delete-tag-prefix doesn't delete tags where the prefix is the entire tag.

Let me know if there is a better import definition than what I came up with or something that I could do on my end to make this work for SDE.

Thanks!

**Comment by orangedrink** [comment]
I think you're aware but I should probably mention that we are committed to having this working by the 30th.

**Comment by daviddurand** [comment]
Thanks for the kind words. It's not my best design in terms of usability, but I tried to pack in a bunch of features and work on making them combinable enough to reuse.

On to your problem:

I think you just need to add a `when:Status!99:` prefix to the add-user-tags entry in the MeetingCode column.

You could also put the `when:Status=99:delete-tag-prefix=MeetingCode` in that field if you want, but either way should work... 

I like putting the stuff for a data item in that column when possible because then I can use `$` in something like `when:Status=99:delete-tag-prefix=$`. Of course the shorter code may be outweighed by the squirrelly syntax.

**Comment by orangedrink** [comment]
Adding when:Status!99: under meetingCode didn't work.

Isn't there a directive to just remove tags?

**Comment by orangedrink** [comment]
We were committed to having this working yesterday. Any idea how soon we can make this work?

**Comment by daviddurand** [comment]
I don't know where you are testing it, so I can't look at the settings file that you are using. I will check it out as soon as you can tell me. The SDE site does not have an updated set of settings, so that might be the problem if it's not working for them.

You might also have a test file or some lines from one, that I can use.

The delete-tag-with prefix can delete a tag by itself, so it is a delete function.

I'm sorry about the timing, but I was supposed to see bug reports by Weds. of last week (extended from Monday, as I was a day late writing the doc.).

 -- David

**Comment by orangedrink** [comment]
I am testing on SDE. How do I make permanent changes to the import definition? 

Here is the import definition:

UserData  
Status  RegistrationCode    MeetingCode     PersonId    FirstName   LastName    EmailAddress    SessionNoSpace
keep    keyword             keyword-list    string  string  string  string          keyword-list
------- ------------            when:Status!99:add-user-tags    id          ---------   --------    -------                 spaced-list when:Status!99:add-user-tags MeetingCode/SessionNoSpace when:Status=99:delete-tag-prefix=MeetingCode

Here is the upload data:
99  123 C123    123456789   David   Franks  dfranks@omnipress.com   a1 a2 a3

The delete-tag-prefix deletes any tag that starts with a value and that's definitely useful but there doesn't seem to be a way to remove a tag when you have the complete value of the tag you want to remove in the meetingcode field.

**Comment by orangedrink** [comment]
I did find the place to put the upload definition so that should be set to what I pasted in my comment above.

**Comment by daviddurand** [comment]
I see that your definition is not working for some reason. I'll look into it to see if the problem is in the software or the definition. If it's a bug and not some weird syntax thing that I'm not noticing, I will let you know.

However, if you use the original definition I sent, it does work, and doesn't try to do anything different from yours.  I'll email the excel file containing the import parameters again.

You have to be careful in testing to make sure that the input is not ignored as already imported. I made two versions of the status 99 record and an import record to add the tags back;  testing was pretty quick using those files in different orders, along with a separate browser window open to the admin, and showing the affected account..

**Comment by daviddurand** [comment]
I found a problem when the field value defining the prefix for deletion was referenced from another field. Fix will be in place tomorrow (but you can still use the original file anyway).

**Comment by orangedrink** [comment]
OK. This is working for us now. I'm using this slightly different definition: 

UserData  
Status  RegistrationCode    MeetingCode     PersonId    FirstName   LastName    EmailAddress    SessionNoSpace
integer keyword             keyword-list    string  string  string  string          keyword-list
trim    ------------            delete-tag-prefix=$ when:Status!99:add-user-tags    id          ---------   --------    -------                 spaced-list MeetingCode/SessionNoSpace when:Status!99:add-user-tags

I removed the when:status=99 in front of delete-tag-prefix so that sessions will always be current.

Thanks David!
