### ISSUE TITLE
SDE email contains "garbage characters"

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#124]
Here is a screen capture of the email I received from the system:
http://screencast.com/t/1C6V1qXW

I've highlighted the problem text SDE is asking us about. To me it looks like a problem with macro substitutions but Ryan set all these email up so I'm not really sure what I'm looking at. 

Thanks David!

**Comment by daviddurand** [comment]
This is an email template problem. %1$s is something that worked a long time ago, and has been removed from the system since the new email templates were developed. Somehow SDE seems to have been set up long enough ago that an old (and bogus) default value was saved for the email template. In any case, it should be easy to fix.

The email templates are all Freemarker templates like several others in the system. The doc is at https://github.com/Tizra/Tizra-Customer-Tracker/wiki/Email-templates-reference 

You can revert any template back to the (correct) system default by simply deleting the value in the settings editor and saving a blank value for mail.activatedaccount. The system default isn't fancy, but will work properly. I'd recommend making a copy of the template that is in place now first, because all the HTML stuff is in place, then reverting to the system template to see an example of the "new-style" templates as documented in the wiki. Then it should be pretty easy to put the two together to get a working, and nice-looking template.

**Comment by orangedrink** [comment]
We've already customized this email template. We don't want to revert it back to the default and frankly I don't think it's our responsibility to correct things in the system that are now broken because you developed something new. Once we build a site we expect it to work in perpetuity without extra work on our part.

Please let me know when this template is functioning as it was before the change you describe and please check to make sure that our other sites do not have broken templates.

Thank you.

**Comment by daviddurand** [comment]
Please calm down.

There have been no changes made to the system default template on account activation since February 23rd. You asked me to turn on the ASPPA stuff for SDE in March, and it looks like it was working in April.  The last email I have was April13th. I don't know why you used template code that was obsolete in February (at the latest), in March and April. I don't know why no-one noticed the problem.

I did make some updates during this process in response to issue #32. It was only two months ago that I put the email doc onto the Wiki, so perhaps the previous email deliveries had left some confusion in someone's mind.

As far as I can tell, the template may never have been correct. I don't know because I try not to edit your content, as I am not in the loop for your customer and design relationships. I don't remember dealing with specific questions on that template. 

I reminded you of the ability to get back to a working default in the hopes that it would be helpful. You can use it as a starting point if you want to. There is no software problem here that needs fixing.

**Comment by daviddurand** [comment]
I have changed the string `%1$s` to `${site.hostname}`, as this conversation is quite unproductive. The problem has to have been of your making, because the rest of the template uses the correct template features -- which did not exist at any time when %1$s would have worked -- so you must have missed it in testing.

My guess is that the string was lost in the markup, as the SDE custom email HTML code is not formatted for human readability.

**Comment by orangedrink** [comment]
Thank you David.
