### ISSUE TITLE
Change of email address in SDE user upload causes account to be reset to pending activation

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#125]
Is there any way to prevent this?

**Comment by daviddurand** [comment]
I think that we should have a set-user-status operation in the import configuration, and that's something we will get to someday soon. That doesn't help though.

I give several alternatives and explanations below, for completeness, but I think the simple answer is really "no". There are some alternatives, but they lead to more problems than they solve, I think.

There's a problem with changing the email address, which is that we can't keep the same password -- as we don't know the password itself. The only thing the system has is the result of encrypting the username and password along with some other stuff -- so it's not possible for us to do that at this point. If we changed the system to make the encryption independent of the account name, then we'd have made it easier for someone to attack the password file.

I can't see a way around this that works very well, especially since a change to password management could have pretty global effects. I agree that this a puzzler to users, and we have been able to avoid it in regular Tizra usage. When people change their email address **from Tizra** system their password does not change. It's not magic, that lets us get around this problem. We require an additional password validation in order to change a password (a common and good practice). It has a nice side effect though: at the moment that we are changing the password we have their original password in hand, just as they entered it (and we validated it).

I am working on some new features for other customers that will eventually enable us to send account updates (like name changes) out from Tizra, but SDE would not be likely to use something like that due to the need for development at their end

SDE could just have people make the change at the Tizra end if they want to, since we  don't have to match on email address any more -- we could have another field to store the email. The problem then is that there would be two email addresses on some accounts, and that would also be confusing. Non-email account names are possible, but also introduce one more thing to remember (and we can't currently send emails from Tizra if users do that).
