### ISSUE TITLE
Static Export Outstanding Items

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#132]
- Still waiting on ability to download PDF files
  This is in our scope of work and is something we need but we still havent seen this yet. Any idea on an ETA?
- Author index not showing full metadata
  The author index work around we're using doesn't seem to show the appropriate metadata.
- Need ability to replace AI link for static export without removing AI from live site..
  For a majority of our customers the standard author index isn't cutting it. We've been creating them as static pages in most cases. This is the same problem I described in #109

**Comment by daviddurand** [comment]
### Author index not showing full metadata

I don't know what metadata is missing, or what workaround you are talking about, and I don't see an open issue that matches this description. I remember that you were trying to put author indexes on a static page at one point, and that is unfortunately not supported. (#66) and then again (#83) .

### macro to check if static export is in progress and allow conditional markup.

(#109) I know that I agreed to add this to the scope, but haven't had a chance as yet.### On PDF downloads:

I keep thinking that we'd decided not to try to move the PDF files (and skip the file transfer charge as well). But in a quick check in the email (I know I suggested that change on the phone) I can only find one written reference, which I intended as a proposal to talk about what might make sense  -- or at least a request for confirmation. Certainly I've not put in any thought on the issue since it's been absent from the issues list. I'm still not happy with any of the options -- S3 involves a bunch of new work; FTP is too attractive a hacking target.

I have recently added some capabilities to WebDAV. Would you be satisfied with a way to copy the files by mounting the site as a WebDAV volume? I think a change could be put in place that would offer a more convenient directory organization for extracting the files via WebDAV.

Here's the last written correspondence I could find on this:

```
David Durand david.durand@tizra.com Apr 25

to David, Abe, slawler 
Oh, I thought we were revisiting the idea of transmitting the files altogether,
since it seemed like a fairly high-cost way to send you data that you already have.
We can bring back the S3 delivery idea though.

```

**Comment by orangedrink** [comment]
I don't think we had noticed the metadata issue on the AI of static exports before now so it makes sense that there is no open issue.

I would post screen captures but I can't since the sites are all down. Basically on the online sites an entry in the author index might look like this:

Durand, David
     How to Tizra
     Time: 12:00
     Date: 12/12/12

But on the static export we only see the name and title:

Durand, David
     Title: How to Tizra

Let me know if you need any further clarification. Thank you.

**Comment by orangedrink** [comment]
Any progress on this one?
In case you need clarification on CE the author index looks like this
http://screencast.com/t/Zd34TsRoQt

But on the static export I get
http://screencast.com/t/AAbMc6gs7BB

**Comment by orangedrink** [comment]
Anything? This Author index issue is still causing us headaches here. 

I'd also like to know if you plan to deliver on the PDF files. We feel like we paid for this and would like to see it delivered.

Thanks.
