### ISSUE TITLE
Untagged Excerpts May Inherit Document Tags

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#136]
In the case where the following sequence occurs, Excerpts may inherit tags from their parent Document...even though the Excerpts themselves appear to have no tags...

1) A Document is created with no tags.
2) Excerpts are created within the Document
3) The Document is tagged (but Excerpts are not)

The workaround is simply to add a random tag to the Excerpts, publish, then remove the tag and publish again.  Once this is done, the Excerpts involved are OK permanently.

This can be done in bulk using the SuperTagger.

**Comment by daviddurand** [comment]
This workaround no longer works, because inherited tags are indexed differently, and the real underlying issue is that inherited values are **both** 
- invisible, so that the tags cannot be seen
- uncontrollable, in that the inheritance cannot be enabled or disabled in any way.

past workarounds built on the failure of document publication to update excerpts, but that fails since index cleanup via title groups was removeing Excerpts from the index.

**Comment by daviddurand** [comment]
closed by 7d6b07cb0c672347540502dc226e29b748eb2188
