### ISSUE TITLE
Getting errors when trying to delete collections and their contents

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#138]
I'm getting rid of some old content on the SDE site. I go into the collection click on documents in the site browser. I select all teh documents in the list view and delete them. It seems to work but after deleting documents I see:
http://screencast.com/t/9y4bbyviSMct

Then on deleting the collection I see:
http://screencast.com/t/dymEM4VY7

The collection is still there. On my second try deleting the collection I see:
http://screencast.com/t/Oq7NKrJLCW4

But the collection has been deleted.

**Comment by daviddurand** [comment]
OK. One problem is that the collection has a malformed tag -- it looks like two tags were separated by commas instead of semicolons. I haven't seen this elsewhere, so I suspect that it was due to typing into the field directly, rather than by the popup tag editor creating a bad value.

The template errors are a separate issue in error reporting related to recent changes in error signaling, designed to make it easier for the administrative tools to Indicate error messages without aborting the current operation, which is what's happening with your attempts to delete the document. A bad query value _should not_ be affecting the ability to delete the document, but the detected error is being thrown in the old way, and that's what's happening.

A fix for both problems should be in place by tomorrow.

**Comment by daviddurand** [comment]
This should be better. I've scaled down the system's reaction to that kind of bad collection definition, and I think I've got the error message template problems. It was hard to test because the error in the collection definition must have been an old one -- I actually had to make changes to be able to create an equivalent problem for testing. For the moment, I've left that capability to create errors in place, mostly because it matches what we do with other fields -- accept bad data, but present a clear error indicating the problem.
