### ISSUE TITLE
License not allowing downloads on AMIA site

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#142]
Members of the Attendee - AS12 account set should be allowed to download source PDF files via license "94610956"

I tested this by adding myself to the account set and trying a download from the testing site but got the paywall instead of the PDF.

Thank you. Let me know if you have any questions.

**Comment by daviddurand** [comment]
I believe that you are seeing this problem, but if the user group and licenses were updated recently, there could be a lag involved, as users may need to log out from the Tizra site and then log in again for them to see new licenses.

I'm suggesting this because I was able to add myself to the group, and to download several papers.

The AMIA member site leaves people logged in for a long time, but I think that logging out from Tizra alone should be sufficient.

Let me know if you can still make the problem occur.

**Comment by orangedrink** [comment]
It's working for me now. 

If there is a lag involved doesn't that cause problems with the SSO? We're getting a lot of support requests from users who can view the documents but not download them.

**Comment by daviddurand** [comment]
The sso should be independent. What happens is that a Tizra session (associated with a login, and a distinct cookie) remembers access results and licenses for things accessed in the session. This is important for performance, because we don't have to round trip to the database on every access checking the 10's or hundreds of possible ways that a user could access a page (collections, excerpts, collections of excerpts, documents), with licenses retrieved based on userid, groups, etc. Once those things are checked during the presentation of an access denied page, those things are remembered for that session.

SSO logins make updates to the Tizra accounts when they happen, and whether something similar is happening at Amia's end is not easy for me to check. I actually tend to doubt that it is.

If there are a large number of continuing issues, I need to know that in case there is something else. Has logging out an logging in repaired the problem for any of the people with trouble? Your first-line support people should be suggesting that. You should also check the specific logins to be sure that they actually are in the group -- problems there would indicate that the SSO is not updating Tizra promptly, and then we'd have something concrete to investigate there.

If you can look into this aspects and get back to me, I can try to see if there is an underlying issue that I can address. Until then, I don't have enough information to proceed further.

**Comment by daviddurand** [comment]
without further info, I'm closing this.
