### ISSUE TITLE
AI SSO Not working properly.

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#144]
I'll forward you the mail that I received from Rick. Basically he says:

 The user gets directed to the “Knowledge Center” site but they are not “logged in” and do not see any of the tags (seminars).

Let us know what you are able to find out.

**Comment by orangedrink** [comment]
Here is a username and password to test with 

rhood
1AIt3st@ccount9

**Comment by daviddurand** [comment]
I'm afraid I will be out of pocket until a little after noon, so see what you can find out. 

I see validation failures in the log, and given the time of year, I suspect that login script is not properly getting the time in GMT. This happened with JSpargo, and I actually had to read their script and discover that they were not calling a system function to get GMT, but simply subtracting from their local time.

My guess is that they went to daylight savings recently, and are using the wrong time to calculate the validation codes. This will probably be an intermittent error, as there's a half-hour window of on either side of the correct time, but a clock that is a full hour off (plus or minus whatever additional skew there may be) will not make the window of validity the whole time.

I saw what I took to be a few isolated validation errors in the logs over the last few days, and if this is the cause they are probably symptoms of a consistent problem, and not just internet flukes. [I didn't see enough errors to notify you (as transient problems may occur, and usually mean little to nothing).]

**Comment by daviddurand** [comment]
Email clipping:

From: **David Franks**
to me, Ryan, Abe 

SSO will have to wait until you're available.
I'm looking into the javascript error but can't reproduce it.

**Comment by daviddurand** [comment]
I was not involved with the developers on this in any significant way. I can talk with them, if that would help, but basically my first question to them would be "how are you getting GMT?" if they are not calling a system function, but instead making a calculation, then they need to get the correct GMT value. If it's not working, even with the correct time being used, then we may have a bug to investigate.

I just checked what was happening with one of the validation errors from the log. Our system was using a GMT-based timecode value of 751329 (Basically the count in half-hours since the Unix base date in 1970).

They were calculating based on a timecode of 751327 -- exactly one hour earlier.

I've double checked: the time on our server is not wrong, and since we are using GMT from the system, that must be correct as well, so it must be happening in their code, which must be looking at some local time -- or their system has the wrong date (unlikely these days, with internet time servers configured into most computers).

**Comment by orangedrink** [comment]
Please get in touch with them to see if that is the problem they are having.

I do realize that you were not involved in the setup of this SSO. This was a bit of a sticking point with me since we did pay you the $2000 to set this up with them. I guess now is your chance. Let me know what you find out.

Thanks!

**Comment by adane** [comment]
David--

We'll be happy for David Durand to talk with the appropriate customer contact if you will set up the conversation.  

As with other aspects of our partnership, it's our understanding that you want to be primary points of contact with the customer and that we are providing Level 2 support.  

Please bear in mind also, that the SSO fees are not just service fees but license fees reflecting the value of our significant investment in the capabilities they provide you with access to.  I believe we had at some point earlier in the year proposed offering more active ongoing support for SSO, but at that time there was not interest on your end.  We'd be glad to resume that discussion.

Thank you.

Abe

**Comment by orangedrink** [comment]
If David could contact him by email that seems to make the most sense at this point. 

Abe would you be able to outline exactly what services are included in the SSO fee? If services like this are not included I think it may be necessary to give us some more troubleshooting tools on this end so that we have the ability to see what might be going wrong.

**Comment by adane** [comment]
The point is for you to set up the conversation, whether via phone or email, with whomever the correct point of contact at the customer is.  

It is not an efficient use of a technical resource to have David Durand try to figure who he is supposed to contact, introduce himself to that contact, etc.  A simple email from your end, copying David will do the job.

**Comment by orangedrink** [comment]
I see. I guess it wasn't 100% clear that the email I forwarded Fri was from the correct point of contact. I sent an introductory type email to get the conversation started.

Any way I could get a brief rundown of who is responsible for what when it comes to SSO?

**Comment by adane** [comment]
OK.  So you want David to take this up with Richard Hrubec?

Obviously what's tough about SSO is that it's hard to standardize, but in general my understanding is that you manage coordination and communication with the customer and any third parties.  We provide advice and input as to approach prior to the sale, then implement once there is agreement.  After implementation, we provide Level 2 support, meaning you escalate problems to us after making reasonable efforts to check that the issue is not with components external to Tizra.  

As a practical matter, a quick phone call with David is often the best way to sort through these issues.

**Comment by daviddurand** [comment]
I did some research on VB.NET and found the system calls to calculate GMT. Richard then updated the script to correctly access GMT, and it seems to be working reliably since.
