### ISSUE TITLE
AI Toggle PDF/Image button not working

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#147]
To replicate log in and visit http://knowledgecenter.appraisalinstitute.org/842-student-handbook/1

Click the black button that has the image icon on it. Second one from the right.

**Comment by daviddurand** [comment]
This page still appears to use the script mentioned in issue #127, which is not supported, and will never work again. For performance reasons alone you should make sure this is removed.

I can tell the script is still in play because in PDF mode I see the image and PDF on the same page (in a broken layout).

The page can be switched _into_ PDF mode, but not out out. This is a problem in your javascript, which you will have to fix, as it it yours. the problem is probably something happening on page load which is breaking jQuery's decoration of the buttons and leaving them inactive. As the markup is a simple link, I was able to inspect it in the browser, and follow the link, at which point the correct page format switch was made.

**Comment by orangedrink** [comment]
It was related to that script. I didn't realize that was still in there. Thanks David!
