### ISSUE TITLE
Static Export Issues

### ISSUE THREAD

**Issue by PStokesOmni** [Tizra/Tizra-Customer-Tracker#148]
With SIAM/52955 I am trying to do a static export of the site, in the .zip file of the export there is only on folder "collections" with one html file that is blank.

Please advise.

**Comment by daviddurand** [comment]
What's the site URL? Is the content published? which design are you using, or is that what "SIAM/52995" means? It does sound like a probable bug.

**Comment by PStokesOmni** [comment]
URL: http://siam52955.tizrapublisher.com/admin/main 
Design: 00000-MOBILE and PDF Controls 
yes, content is published.

**Comment by daviddurand** [comment]
It's fixed (and live).

There was a macro problem in a call to `%IF_CONTEXT_VALUE_BEGIN(METADATA_VALUE:a,b)` I could not find the exact call (too many master blocks) to check if the problem was your syntax or a system failure on checking a missing property, but I fixed the crash, and it seems to be exporting reasonably at this point.

If you see something funny in the export, you may want to check the macros at that point in the design, in case it was a problem in the markup.

**Comment by orangedrink** [comment]
We're missing metadata in the TOC now.

The live site looks like:
http://screencast.com/t/sH65RHBvIdEJ

But the export looks like:
http://screencast.com/t/xdm7sSKL

**Comment by daviddurand** [comment]
You had set the MetaType on the list blocks to "Document". That types is actually just like the book metatype, but does not get get extended when you add fields to "Book". The static export (because it's offline) is a bit more restrictive in how it formats list entries, as it is driven entirely by the delcared type. 

Since the  purpose that the "Document" type once served is now completely extinct, I'll remove it from administrative menus, so that the same mistake should not happen in the future. If we did not have to remain compatible with old sites, we could clean up the types and type names, but for the time being we cannot do so.

If you fix the rest of the blocks to the value "Book" the static export will work (I tested with the first 5 or so updated).
