### ISSUE TITLE
CMBA can't edit or delete a collection

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#160]
To reproduce go to the admin panel for http://knowledgecenter.clemetrobar.org/

Go to collections and try to edit the collection named "White Collar Crime in America and the World: The Experts Speak" which is NOT tagged with 'event' or 'USE THIS ONE'

**Comment by daviddurand** [comment]
It's working now, and so I can't replicate the error. Checking the logs does show errors on that collection around 4:20 and after. These errors indicate that you deleted a license, and that the database cache was stale, so that the license referenced in the cache was not there in the database.

I'll look into possible underlying causes. In any case, with recent caching changes, this should clear spontaneously in no more than an hour. Because licenses need to be aggressively cached for access control to perform well, there are sometimes problems when deleting licenses (a relatively uncommon operation, fortunately).

In any case, on a live site it's usually better to just disable a license by expiring it, especially if there's a chance that it applies to any logged-in users, as sessions have thrown errors in the past from deleted licenses. Currently that particular issue does not happen, but it's better to be safe sometimes.
