### ISSUE TITLE
Filter list broken on TRB document screen

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#165]
To reproduce go to the admin panel of amonline.trb.org and click contents. Click Create list filter and then on the filter list input. 

I'm getting various error messages. Seems to be a different one every time.

Thanks.

**Comment by daviddurand** [comment]
This seems most likely to the same cache issues as  #166, since I can't replicate this problem either. Stale cache could lead to a number of issues, depending on the exact access history of the relevant data, which may also make some sense.

I was able to filter on admintags and Year in the document list.

I am closing this issue -- followups if any should go to #166.
