### ISSUE TITLE
URGENT: Static export of site http://bps2013.conferencespot.org/ produces invalid zip file

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#167]
After export I get this error message when trying to open the zip file
http://screencast.com/t/3qElCQYtRdr

I need to get this export done today so please hurry.

**Comment by orangedrink** [comment]
Also please make sure that macros are working properly on the export. Using some command line utilities to try to fix the zip allowed me to see the index.html file and it looked like macros were all missing.

I put the macro in like this:
http://screencast.com/t/49CqZF6ZPg

But my code comes out looking like:
http://screencast.com/t/mdMw7pfU72

it looks like a similar story for the design properties that we use for colors, home page text etc.

Thanks!

**Comment by daviddurand** [comment]
I'm working this, but the export is huge, and I'm having trouble tracking it down.  I'll keep you posted.

I'll work the parameter problem once I find the file format issue.

**Comment by orangedrink** [comment]
OK thanks

**Comment by orangedrink** [comment]
I talked with the project manager on this job and it sounds like as long as this is ready for me by Monday we will be OK.

Thanks!

**Comment by daviddurand** [comment]
I have found the problem with the invalid zip files. I am working the macro issue. The problem is that the web server was gzip-encoding the zip file, not only is this useless, and does it make the server slower, but it can occasionally introduce errors depending on particular character combinations that can show up in the zip file before gzip compression....

This problem had probably manifested earlier as a few difficult-to-reproduce errors. The size of the site export on this site pretty much ensured that if there was a character sequence that would cause errors, it would show up. I made a variant of the site with a blank index page template, because the giant author/title indexes don't seem to be being used, though they look OK. You can use your own design if you prefer, but this will ease my testing.

**Comment by daviddurand** [comment]
macros are being replaced properly as well.

**Comment by orangedrink** [comment]
I'm not getting the title macro at the top of each collection page. 

I put in "&lt;h1>%TAG_VALUE_OBJECT(Title,)%&lt;/h1>"

But I get "&lt;h1>&lt;/h1>" in the static export.

I need to have this finished today so please hurry!

Thanks!
-Dave

**Comment by orangedrink** [comment]
I can't find any other macros that aren't working properly.

**Comment by daviddurand** [comment]
Whoops.... This is not exactly a bug, but it would be pretty hard for you to have figured out.

 The problem is that Collections have "names", which are not normal properties at all. There's a special exception in place for the "Title" property on collections, which will return the name of the collection as the default value if there is no property named "Title" defined on the collection.... You can see this in two places:
1. The field is not actually called `Title` in the interface, it's called `Name`.
2. Like offer names, and the queries that define the contents of a collection, there is only one value for a collection's name, so that changing the name of a collection takes effect instantly across both stagin and live sites.

Aside from collections, the only other places this kind of behavior shows up is for Static Pages, and Offers.

I can try to make a larger fix at some point, but right now there's a quick fix you can do yourself:
1. Create a new property for Collections and name it `Title`. Give it type Text, String, or HTML, as you prefer.
2. republish all the collections from the list view.

That should do it.

If you still have trouble, select all the collections and run the super-tagger without making any changes -- that will ensure that each of the collections is properly reindexed.

From that time on, you'll have to change the "Title" instead of the name.

**Comment by orangedrink** [comment]
Hmm.. There are a few hundred collections on this site so going into each one to add a title isn't very practical. Is there a macro I can use to pull the "name"?
