### ISSUE TITLE
Seeing problems with bypass TOC feild in TRB upload

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#174]
I'm hearing about a bunch of cases where it seems that the bypass toc setting was set incorrectly in the first TRB upload we did early this month. I'm having to correct the settings as soon as I hear about it so hopefully that doesn't cause problems for you when trying to troubleshoot.

So far I've had to correct 13-1051, 13-3994 and a couple of others that I would have to dig up. Looking in the upload data I sent it looks like these should have been set to bypass the toc but they were not.

Any idea how to make sure that there are no others that were set wrong?

**Comment by daviddurand** [comment]
I believe that we had some email back and forth on some fields that were string values, with "yes" being special, rather than a true/false. I sort of remember doing some conversion (case conversion, maybe?). If you think there may be problems, you should just export the 2013-tagged articles, and check the values.

**Comment by orangedrink** [comment]
I'm not that fond of having to check your work but these are the ones that were incorrect:

13-1191
13-2206
13-2661
13-3422
13-4737
13-1723
13-1991
13-2893
13-3127
13-4565
13-5236
13-5184
13-4288
13-4684
13-0108
13-0514
13-0533
13-1356
13-2124
13-2138
13-5362
13-1946
13-2952
13-3426
13-3434
13-3564
13-3731
13-3748
13-3905
13-4247
13-5252
13-5267
13-5347
13-1155
13-1062
13-1243
13-1365
13-2753
13-4650
13-2917
13-5249
13-4442
13-5287
13-5235
13-2082
13-1432
13-2109
13-2080
13-1549
13-4192
13-5151

**Comment by orangedrink** [comment]
Please fix them

**Comment by daviddurand** [comment]
I've checked the history, and it seems that your spreadsheet used the values "True" and "False" instead of the standard values "true" and "false" as used throughout tizra, including the export files. However, I agree that detail is not documented in the metadata cheat sheet.

I think I can make a pretty quick fix in this case, and I am willing to because of the documntation issue on this detail, despite the long elapsed time -- but I want to be clear that we have never claimed that a bulk import may not have errors due to irregularities in the input.  _I agree that the process is both too manual and occasionally has gotchas. (This is one reason that an import facility with a lot more error checks, and that you can use directly is so important to us)._

While we do touch your data in this case, responsibility for data has to rest with you, as we cannot know everything about what you want for hundreds or thousands of records. We expect that you are _always_ checking the work. That might not mean proofing every record directly by hand, (although you could probably do a quick check by using excel to compare your import file, and an export after the load).

With that in mind, I'd like to clarify that we will observe a one-week time limit on checking the data, from now on. You will need to proof your data to your satisfaction within that week, if you want us to repair a problem.  Obviously if there's a special issue with checking, we could extend this time, on special request. Otherwise, if we don't hear anything, after a week, we'll assume that the results have been accepted.

**Comment by orangedrink** [comment]
Thank you David. Hopefully with the new import things like this won't be an issue.

**Comment by orangedrink** [comment]
You said you would fix this. I'm still getting reports of papers on this list that are not set correctly.

**Comment by daviddurand** [comment]
I've fixed the remainder, and checked the rest to the best of my ability -- assuming that TOC is only needed when there is no PDF available.
