### ISSUE TITLE
Trying to edit collection Home layout

### ISSUE THREAD

**Issue by PStokesOmni** [Tizra/Tizra-Customer-Tracker#175]
I get the following error message popup when I try to edit the collection home for the table of contents collection on neta53976.tizrapublisher.com

Request failed. Error sent back: >><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
    <head>
        <link rel="stylesheet" href="/aa_admin/aa_styles/tizra.css" type="text/css" title="default" />

```
    <title>
            Unknown Tizra Error

    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="shortcut icon" href="/aa_images/favicon.ico" type="image/vnd.microsoft.icon" />
</head>
<body>
    <!-- Begin Banner Block -->
    <div id="banner">
            <div class="banner-title"> Publisher for NETA/53976 </div>
        <img id="logo-spray" src="/aa_admin/aa_images/logo_spray.gif" width="44" height="25" alt="Tizra" title="Tizra" />
        <img id="logo-tizra" src="/aa_admin/aa_images/logo_tizra.gif" width="61" height="25" alt="Tizra" title="Tizra" />
    </div>
    <!-- End Banner Block -->

    <div id="content">
        <h2 class="exceptionMessageText">Error:
            Unknown Tizra Error
        </h2>
        <p>If this looks like a bug, please send us a note describing what happened, and we'll try to get things fixed as soon as we can.

            <a href="http://tizracustomersupport.wufoo.com/forms/tizra-customer-support-and-feedback//def/Field10="
                 action="email_click" /]"
                target="_feedback">providing us details</a> on the steps leading to this error.
                We'll get back to you as soon as possible.
        </p>
    </div>

    <!-- Begin Footer element -->
    <div id="footer">
        <p>
            <a href="http://www.tizra.com/" id="a-footer-privacy">Privacy Policy</a> &nbsp;<span class="pipe">|</span>&nbsp;
            <a href="http://www.tizra.com/" id="a-footer-terms">Terms of Use</a> &nbsp;<span class="pipe">|</span>&nbsp;
            <a href="http://www.tizra.com/" id="a-footer-about">About Tizra</a>
        </p>
    </div>
    <!-- End Footer element -->

</body>
```

</html>
<<

**Comment by daviddurand** [comment]
I don't see a table of contents contents collection on that site, but I am getting an error when I try to edit the main home page template. The error actually occurs on any attempt to edit a template.

I tried saving a copy of the staging state and reapplying it, which can often clear an error in the layout, and that did not fix the problem.

I traced it to a database inconsistency in the workbench setup -- Not sure how this happened, but I have fixed it.

The layout editor provides instant turnaround, and that means that the database use is a little different, so you should try to make sure not to have several people editing the site presentation at the same time -- but that is not the only way for a problem to occur. There are several known bugs in the presentation manager that we have not been able to track down because they happen so infrequently (a few times a year) and we have not been able to figure out how to replicate them. If you can remember anything unusual that you observed or did before the error started, that would be helpful.
