### ISSUE TITLE
Status Pending Activation not working correctly

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#185]
It is working identical to email verification required.

http://experientenvision2013.conferencespot.org/

**Comment by daviddurand** [comment]
A fix is in place, and will be live tomorrow.

The user interaction was actually sending the message, even though the password was being set and the account activated. Unfortunately the results are delivered as a secure page (because of the password submission), so the user's login cookie was not being properly set for the actual site.
