### ISSUE TITLE
Unable to upload PDFs to TRB site

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#196]
Tried to create a new document by uploading a PDF three times this morning, each time got this message.

"Error: We're sorry, we were unable to process your file. Tizra Publisher only accepts PDF documents at present, so please verify that's what you tried to upload. If you continue to have problems, please contact <a href="mailto:publisher-support@tizra.com">publisher-support@tizra.com</a>."

**Comment by daviddurand** [comment]
Pdf files are working in general, I just checked. The likelihood is that there is something wrong with the PDF file. First make sure that you can open it with acrobat. If you can open it without errors in acrobat, then we'll need to look at it, so email it, or let me know where it can be downloaded.

Because of the PDF processing problem, the file was not saved properly on the system, so I can't check it from the database.

**Comment by aabercrombie** [comment]
The PDF is working now. Must have been a temporary glitch.

**Comment by daviddurand** [comment]
Perhaps there was an upload error and the file was corrupted. I've certainly never seen this message when the file contents was valid. In any case, glad it's working properly.
