### ISSUE TITLE
Users reporting log in problems. Screen grab attached

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#210]
Hi David. It seems there are some issues for users logging in to http://aaos54273.tizrapublisher.com

I got this message today:

> For the AAOS site we just completed It seems that when users are activating their 
> accounts, their Tags are being removed.  When the users then try to access the materials, 
> since they have no tags, they are denied access to everything.
> 
> This doesnt seem to happen for everyone, but I have found about 10 in the last two days.  I 
> will check all users and confirm they have tags, then a half hour later I will find 2 or 3 that 
> have gone missing.  We have already gotten 2 or 3 support requests related to this.  

This is a site where we are using the simple "Bulk creation (form entry)" method of creating accounts. To test this I created an account for myself using this same form and the tag "participant". I immediately clicked the link sent to my email and saw this error message: 

http://screencast.com/t/5pmOWyjbetcJ

Thanks!

**Comment by daviddurand** [comment]
The cookie/session problem must be a cookie or session issue. Maybe you were logged in as an admin in the browser, or the link is being bounced from one handler to another (Windows sometimes does this, at least when Office is involved).

I was able to create an account manually and with the simple loader and had no troubles activating it as I was supposed to.

Could you have had multiple loads going at the same time? Maybe the search index got off, and that left a few accounts in trouble...
I'll reindex the User accounts on that site, just in case.

Is there an account that is in a bad state that I can investigate? otherwise I won't be able to do much, unless you can tell me how to replicate the problem.

**Comment by orangedrink** [comment]
Thanks David. We'll work on getting more details around this.

**Comment by daviddurand** [comment]
I made a test group with the predicate NOT: faculty;participant

It's a short list:

```
kerwer@aaos.org      staff
mazur@aaos.org       staff
Unnamed account      agilepdf_crawlers
domiyi@yahoo.com     particpant
```

 are two staff accounts, and one other shows up which has the tag `particpant`. Perhaps that is the last of a few accounts loaded with the wrong tags?

We should also see if there is any correlation between the tags that should have been on the accounts that are showing problems...

**Comment by koldenburg** [comment]
Hi David,

I was able to track down a couple of the user emails which had the problem this morning.  Sure enough, one of the emails the customer gave me is `domiyi@....`, which was identified in your test group.

Another email to look into is: `pmkkane@...`.

Please let me know if you should find anything. 
Thank you,
Kai

**Comment by daviddurand** [comment]
The account is configured properly now, of course, so I don't know what the tags may have been before the owner called and you fixed things.

Looking for `pmkkane@...` in the logs, I see that the account was activated at 1PM yesterday. There were no errors in activation, and the account logged in a bunch of times after that.

I don't see a pattern of cookie problems, either.

Given the state that we observed for `domiyi@...` my guess would be that there were a few accounts uploaded in a separate batch with the `participant` tag mistyped. It would be interesting to see if there were any accounts with problems that were not supposed to be in the participant group, as opposed to one of the others.

I do see an erroneous tag showing up in the prompts: `participant%3Bfaculty`. This is is a remnant from my testing, and is not attached to any accounts.

I just fixed the  `domiyi@...` account and I would bet that this is the last we hear of the problem -- so I suspect that it may have been data entry.

I'm going to close this, on that assumption, but feel free to re-open (or ask me to) if you see any more difficulties.

One thing I've noticed in the logs is that AAOS got a lot of search engine juice with their first site `aaoscoursematerials.com`.  Crawlers are still hitting it hundreds of times per day -- for publicity reasons, they may well want to keep that URL live as their main delivery URL (and leave the content up) -- they could then have the new, course-specific URLs redirect to that, if they want them for usability. Just a thought...

I'm also trimming the exact email addresses out of this thread, as it's not very private.

**Comment by koldenburg** [comment]
I logged in this morning to the AAOS site and discovered a new user account where the tag of "Participants" was dropped off.  I have not added the participants tag back in yet in hopes you might be able to see what is going on.  
- I noticed the account now has a user set of "Missing tags".
- The account is for a Jose Toro (jbtoromd@gmail.com)

**Comment by daviddurand** [comment]
Thanks, I found a bug that is resetting tags when they update their passwords. Fix will be coming. You can reset the tags on anyone that has the problem until we have the fix in place.

**Comment by koldenburg** [comment]
Thank you for the update David.  Let me know when the fix is in place.
-Kai

---

Thanks, I found a bug that is resetting tags when they update their passwords.
Fix will be coming. You can reset the tags on anyone that has the problem until
we have the fix in place.
—
Reply to this email directly or view it on GitHub. <

Kai Oldenburg
Project Manager
- My Bio/Pics
- Looking for helpful tips? Subscribe to Our Blog!

OMNIPRESS
2600  Anderson St, Madison, WI 53704 | office:  800-828-0305 | fax:  608-246-4237
www.omnipress.com

**Comment by orangedrink** [comment]
Thanks David.

Is That fix coming soon or would it be a good idea for us to disable changing passwords for the moment?

Is this currently affecting all of our sites?

**Comment by daviddurand** [comment]
The fix is already in place, so no more accounts will be affected. I am going to see what I can do about finding affected accounts. It did not seem to happen on every account claim (since most folks did not have the problem), just ones where people later went to the update form to reset their password after the initial claim.

It may not feasible be able to get complete information anyway, as we don't log the contents of forms (for obvious security reasons).
