### ISSUE TITLE
Getting various errors when uploading files

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#211]
Trying to update files on s114630228.tizrapublisher.com (ACMA). Have been getting a series of errors ranging from a 404 error to an 'unknown Tizra error' to a couple different versions of a Tizra pop up box error.

**Comment by daviddurand** [comment]
There's not enough information to help me on this, but by picking through some of the error messages, I See a bunch of failed attempts to upload and publish a file(that ACMA board of directors, etc), in one operation. They were specifying the custom URL ID "7B-Presentation1" ,  -- and there was more than one such document. Since that is supposed to be unique, this was creating problems.

I've added a constraint to the database that will prevent that issue from being able to occur.

Because I had to update the database directly, you may see apparent duplicate urls on that document until the caches clear out -- but if you attempt to update them, a new url should be made.

**Comment by aabercrombie** [comment]
So that seemed to work, but now we're getting another set of errors. We created a new document, entered all the information, and tried to upload a file. When we hit upload, it gave the 'unknown Tizra error, please contact us' link again. I hit refresh, mostly just to see what would happen, and got back to the document page where it looked like the file was now uploaded. However, when I hit save, I got this (see screenshot below.)
![acmaerror](https://f.cloud.github.com/assets/3876308/359375/7c7d1720-a15d-11e2-990c-78040628893f.png)

**Comment by daviddurand** [comment]
I saw the error in the logs, and came here in order to post an update -- then I saw your post. The problem on this page is a duplicate Custom url again. That's why it says ConstraintViolationException. Why don't you do the uploads without the custom urls, and try entering them afterwards, since the old loads have left various duplicates around, and the error is then leaving you with a messed up document. You can also upload the PDF into a failed load by using the add pdf area at the bottom of the document page -- better than re-uploading a new document, especially with the duplicates creating trouble. Also, the caches get messed up on these kinds of errors, so that may make things tricky, and they take an hour to clear out...

**Comment by daviddurand** [comment]
It's hard to tell, but I don't see any errors that are not caused by duplicate custom URLs in the logs for the last hour or so....

**Comment by aabercrombie** [comment]
It was the duplicate URLs again. The system wasn't showing the new documents in Firefox for a while, so I thought they weren't taking. When I switched to Chrome, the 6 or 7 documents suddenly showed up. When we got those back down to one document and deleted the rest, we were then good to go.
