### ISSUE TITLE
User information

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#218]
We have a school district that was wondering if their teachers are actually using our curriculum. They were wanting to see if we could tell if they were logging in or not. Is there a way that we can see this information? I looked under reporting and got a detailed report for "User Activity" but it just shows what's been done on the admin side, like creating new users and such. If there's a way to see this info, that'd be great! Thanks!

**Comment by daviddurand** [comment]
The "detailed" download stats give a report on file downloads (which does not include individual page views). The logs have not been used very much, and are still pretty rudimentary. They are really still very much a first implementation that has not been revisited because people haven't been asking about it, but I it does not have to stay that way.

One reason that this has been this way is that most people just use google analytics. You just added a GA account, but one has been in place since 2011. Abe set it up, and I think can grant you access...

**Comment by Kuhrt** [comment]
Yeah, I think what I could pull off of GA will be fine with the location details it has. Just wanted to make sure I wasn't missing something that could give me info per account. Thanks!
