### ISSUE TITLE
Access Key Code (Redemption Codes)

### ISSUE THREAD

**Issue by GWPublisher** [Tizra/Tizra-Customer-Tracker#219]
We have a few issues with a customization that we had.  We are starting to get calls on 2 separate issues with the Access Key Code (Redemption Codes) customization.  The first is users still see the offers when they are on the TOC page before they enter their textbook.  The second issue is that in the Purchase History, nothing shows up after the keycode is entered.

**Comment by GWPublisher** [comment]
This is working great!  One minor thing, in the purchase history, can the title of the batch name be replaced by the offer on the account set?  If not, we will need to replace our batch names.

**Comment by daviddurand** [comment]
The problem is that in principle adding a tag to a user could grant membership to more than one set (and they could have multiple licenses) -- it could even remove someone from a user set (via a "not" match).

Account sets do include a blurb that shows up in the bookshelf/license list. I was thinking that I might include a list of groups that match just the tags set by a code. Would that do?
