### ISSUE TITLE
Account Claiming Bug

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#22]
Tested on SDE. Unsure of other sites that may be impacted by this right now.

Problem: 
When someone tries to claim an account for sde, it gives an error after you create and confirm your password. Although an error comes up the username and password are still created, but all of the errors are causing substantial issues for the end users.
Only way for you to really understand what is happening is to watch the video... http://screencast.com/t/0FUgvhMgcRyA

**Comment by daviddurand** [comment]
Thanks for this good report. The movie is an excellent touch. I found the problems in registration yesterday, which were due to the email updates, and were in fact affecting multiple sites -- I should have logged the bug myself, so that you guys would not be taken by surprise.

The restart this afternoon included the fix.

**Comment by ghost** [comment]
I couldn't think of any better way to explain what was going on.

I just tested this out on SDE and it is working correctly again. Thanks.
