### ISSUE TITLE
Metadata on Indexes on Export are in a different order than site

### ISSUE THREAD

**Issue by PStokesOmni** [Tizra/Tizra-Customer-Tracker#220]
s117335400.tizrapublisher.com
The meta data fields are there, but not in the same order as the site.

**Comment by daviddurand** [comment]
This seems to be a CSS issue, where your site design is depending on some compatibility markup for the design. It looks like you are using the "t-old" classes and elements in your static export design -- and your  live site design. These are slated to be phased out at some point, and have never been part of static export. The default Tizra designs have some standard page header markup that suppresses all the t-old tags, and enables the t-new tags. The relevant CSS that it puts inline is this:

```
.t-new  {
    display:block;
}

li.t-new {
    display: list-item;
}

.t-old  {
   display: none;
}
```

I don't see that standard boilerplate in your page header for this site. The old-style metadata was a limited set of properties in a fixed order, where the new style markup more fully respects the tag ordering and visibility set by the admin. If you update your design not to depend on the t-old tags, you should be able to control the order of the properties using the admin tools to be whatever you want.

Any element with the class t-old is supported only for compatibility with old sites. I have enabled the custom site setting "Generate old-style Tizra markup", so that you can suppress these tags entirely if you wish. We may wish to include that setting in every static-export enabled site, so that you can suppress those tags in all designs, and not end up with this kind of issue in the future.

The site export has never supported the old-style tags -- and will not do so. You should be able to update the CSS and any property ordering pretty quickly.
