### ISSUE TITLE
Export of Commerce Data bug

### ISSUE THREAD

**Issue by GWPublisher** [Tizra/Tizra-Customer-Tracker#227]
We are getting a Tizra error when we are clicking the Export of Commerce Data button under Tizra Publisher Reporting.  We are not able to download anything.

**Comment by daviddurand** [comment]
This was an issue with the new commerce logging for redemptions -- For right now I've updated the records so that the export will work, and we'll adjust the logging so future redemption records won't cause further problems. Will close this issue once the code fix is live. With the data fix in place you should be able to export the logs.

There is also something weird happening with the filename on the export, so will look into that as well. As long as you rename the file, things are good though.

**Comment by GWPublisher** [comment]
This bug has come back, we can no longer download the file.
