### ISSUE TITLE
Maxlogins has a date picker?

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#231]
I'm trying to trouble shoot issues with the account for bob.eastwood@nrservices.com on elibrary.asppa.org and I'm wondering if he's running into a concurrency issue.

I'd like to try upping the limit on maxusers but I cant make sensible edits to this field other than choosing a date.

Here's a video in case you don't understand what I'm saying.
http://screencast.com/t/SIi8c3dxv

**Comment by orangedrink** [comment]
Derp. It looks like this is configurable by us. I bet one of ASPPA's staff changed it accidentally.

**Comment by daviddurand** [comment]
I see you closed this as I typed.

maxLogins is just a metadata field on the User record. Not sure why it is there, or why it's defined as a date. It's under your control. It might have been created as part of user data import in order to construct a tag name.

If you want to limit concurrent accesses, you limit the license under which someone is using a resource. An account can be logged in an unlimited number of times, but the sessions of that account will not be able to use a license if it's concurrency limit is exceeded by other instances of the account.

That's the way it has to work, since institutional accounts are logged in by IP range, and there may be several products they have licenses to, and those products may have different concurrencies.

You may want to delete the maxLogins property; at the least you could change it to a number. Either way, it's not really going to do anything...
