### ISSUE TITLE
Problem applying live to stagging

### ISSUE THREAD

**Issue by PStokesOmni** [Tizra/Tizra-Customer-Tracker#234]
On site s92834083.tizrapublisher.com, when I apply the live presentation library to stagging nothing happens.

**Comment by adane** [comment]
We're looking into it.  It may be something specific to the design.  When I load other designs into staging they seem to work OK.

**Comment by PStokesOmni** [comment]
Any updates? I need to access staging items because I cannot make them live yet.

**Comment by daviddurand** [comment]
The design name had become very long (> 255 characters), as you had gone back to a backup version, then made new versions and so on (so the name had many `(backup date)` strings tacked onto the end. This hit a limit in the database, and was creating trouble. I shortened the name because the information was not really useful anyway, but I have also fixed the database limit, so that it won't happen again no matter how long the name may become.

**Comment by SeanLawler** [comment]
Thanks guys!
