### ISSUE TITLE
License Issue with ASPPA Site

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#239]
When I attempt to save a new license for a user I get the following error:
Error
com.cubchicken.common.control.TizraException: email error
on operation view

But it appears to add the license even with the error.
I need this cleared up as soon as possible.

**Comment by ghost** [comment]
The exact same error occurs when you try to delete a license.

**Comment by daviddurand** [comment]
We had to make a quick configuration change yesterday because one of your conferences was generating very high registration traffic, and exceeded our delivery limit. I moved over default delivery to Amazon, where we have much better quotas, and more important, monitoring tools, but some of the sites with custom email setups started to pick up pieces of the new configuration. I just fixed ASPPA and SDE, and will be looking through the database for any others that may have been affected. If you have a list of sites you know may have issues, then I can get them even before I'm done tracking down the database stuff.

**Comment by ghost** [comment]
I think that SDE and ASPPA are the only two with customized email setups. 
Is there anything other than email service that could make an impact to a site?

**Comment by daviddurand** [comment]
Not sure what your question is exactly. The original impact was just registration traffic (and that level of traffic should have been fine, though it was definitely high (more than 1 registration per minute, at least in bursts). Outgoing email demand was one reason why we had the custom setups on SDE and ASPPA if you remember.  This was definitely our problem to avoid, and I intended to change to Amazon SES some time ago, but kept putting it off in case of creating problems during the transition. The SDE and ASPPA setups were not at fault, just some issues in changing the rest of the world over.

It never hurts to let us know if you anticipate any kind of big surge in demand, data transfer, data storage, etc. We can scale things up, but it can help to know to be on the lookout. We also monitor resource usage, so this was a pretty unusual event.
