### ISSUE TITLE
Navigation Links on Secure Pages (secure.agilepdf.com)

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#24]
http://screencast.com/t/Fme6W9mg8xt

Shot a quick video of the issue.
The Navigation is created by tagging a static page with "nav" to display in the top navigation. 
David F says that it should link to the correct location, but it doesn't seem like the system is doing it correctly.

**Comment by daviddurand** [comment]
## The correct way to make these links:

Use the home macro to generate the right base URL, so that the link won't jump between staging/testing/live by mistake -- and also so that it won't _stay_ on the secure site, which is something you don't want.

So you had links like

/erisa-outline-book/

which were breaking. The macro includes the trailing slash, so you could make links like this:

%URL_SITE_HOME%erisa-outline-book/

If you don't mind the double slashes in the result, I think this is clearer:

%URL_SITE_HOME%/erisa-outline-book/

# original explanation, with less-good workarounds:

Relative links on secure pages that are generated by smart blocks include additional URL components that let the server distinguish the site -- This isn't a problem on any URL that contains a Tizra Id in the URL.

There are very few pages that currently show up from the secure server (and I've been trying to reduce that number).

It's also possible to present those pages in an iframe, or without navigation to avoid the need

This is a pain for me too, and I've been trying to reduce secure page delivery to browsers, because we don't transmit really sensitive information to the browser except in e-commerce transactions.

One way to solve this is to add a URL component to the nav URLs. There's a TizraID for the site itself (the numbers and letters that show up in in the admin page secure URL. For instance, for TRB, it's 10u3t4. Another approach is to create links for global nav using the Tizra ID for the object rather that its custom URL, but then you won't see the custom URL when the link is followed.

For image links and stylesheets you should always use the extra URL component, as in: 
/10u3t4/trb-logo/~stream 
You can get these links from the site admin in the image manager. They show up in the property view under the heading "Relative URL for HTML". They will not give security warnings on HTTPS delivery, and won't break.

One "fix" _not_ to do, is to put the non-secure URL in place. For images, stylesheet references, or scripts it will generate security warnings, and for links it will make the testing and staging sites hard to use by switching sites whenever the user hits the global nav buttons.

I'll label this issue an enhancement, as future changes may make this a bit easier, but this is how it works.

**Comment by ghost** [comment]
What I don't understand is this.

On http://elibrary.asppa.org all of the sidebar links work from the https://secure.agilepdf.com/1v3ibr/~userInfo page, but none of the top links do. 
Both the top and side links that go to another page or document utilize list blocks, pull pages in with tags, and have custom URLs.

They should behave the same but don't.

**Comment by daviddurand** [comment]
No, they should not work the same, because the syntax of the link URLs is not the same. As I explained, a Tizra ID is needed on a secure page URL for it to work for page display.

The links are resolved by the browser.

On this page relative links without a / at the beginning will be relative to:

> https://secure.agilepdf.com/1v3ibr/

which includes a Tizra ID.

Absolute links (with a leading slash) will be relative to the server:

> https://secure.agilepdf.com

Thus they will lose the Tizra ID, and won't resolve properly.

I just checked and this is what seems to be happening. 

for instance, I see links in the nav bar like:

/erisa-outline-book/

You have to look at the HTML source, as browsers will copy the full result URL, not the original markup.

This is just the basic way URLs and HTML work.

As I explained, Tizra URLs on the secure site must include a Tizra ID of some object from the site, or else the server can't tell what site's custom URL might be relevant.

List blocks, etc. sometimes generate absolute links, and sometimes relative links (depending on the situation). Because the server has full information to make the choice at page delivery time, it can always generate a link that will work on that page. If the same page is delivered from another URL (like secure, or staging), it can generate a different link in that case.

The static links you generate have to work with all the URLs of the pages they may appear on.

**Comment by ghost** [comment]
List blocks, etc. sometimes generate absolute links, and sometimes relative links (depending on the situation). <--- This makes zero sense, but since you brought it up, it would be very helpful if you document the situations that it generates an absolute link versus a relative link.

**Comment by daviddurand** [comment]
Well, it's not very informative, I admit, though I do think it makes _sense_. Very few of the relevant "situations" even relate to things that you can see as a Tizra user or administrator.

The variations are internal coding matters, depending on what what part of the system is generating the link, what information is available, whether that link is generated by old code or new code, freemarker or Java. The exact format generated by each block has been affected by many factors and just plain history (we try not to change things like that more than we have to).

The system generates links in hundreds of places, and I could not easily give you a list of which kinds of URLs show up where. Some URLs (for session management, login, logout, etc.) have very sensitive requirements based on browser behavior. Recently, I've been moving generating absolute links in most cases, because they are less prone to interference from the source URL -- and because I know a lot about the source URL at the time the URL is created. That's a practice that works exactly the opposite way for the links you create. Because manual link management should always leverage relative URLs as much as possible, otherwise maintenance and testing are almost impossible.

Also, except generated URLs within smart blocks are subject to change. We don't make guarantees about what the links we generate will look like, and we have, in fact, radically changed URL format once without breaking sites, and with minimal layout changes. What we have done over time is to accommodate people's interest in managing some kinds of links directly in HTML by making all the URLs simpler, and making it possible for reliable relative links to be used for certain things.

Secure pages and URLs are tricky in more than one way -- for instance I get security warnings on ASPPA secure pages because you are loading Javascript via HTTP (from Amazon I assume).

When would the format of a generated Tizra URL ever matter to you? I don't really understand. If there's a use case there, I'd like to be able to keep it in mind.

**Comment by daviddurand** [comment]
top comment has been edited with the (very simple) solution to the problem added.

**Comment by ghost** [comment]
David, That macro is very helpful, thank you.

**Comment by daviddurand** [comment]
Sorry you didn't get it earlier -- I got fooled into thinking my edit
would let you know.

It's an annoying problem, but not too hard to deal with -- I use so
many tools that are different from what you are using, that I managed
to overlook the obvious!

---

David G. Durand
CEO
Tizra
9 Catalpa Road
Providence, RI 02906

Email: david.durand@tizra.com
Phone: +1 401 935-5317
FAX: +1 401 273-5171
Web: http://www.tizra.com/
Blog: http://blog.tizra.com/

Online publishing unbound.

On Fri, Feb 17, 2012 at 4:18 PM, Ryan Hood
reply@reply.github.com
wrote:
