### ISSUE TITLE
Large books getting slow in IE

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#247]
I had one of our customers call me today saying that the further she looked (about 20 pages) at one of our books, the slower it got to change pages up to 15-20 load times. She is using IE so I thought I'd test it, and sure enough (it took me about 50 pages) it slowed down to about that slow. It does it a little in Chrome and Firefox but not nearly as bad. A simple refresh fixes the issue instantly and is fast after that. I still wanted to see if you guys might know what's going on and if there was a way (setting or something) to fix it on her machine. Thanks!

**Comment by daviddurand** [comment]
Thanks for this. I am pretty sure that it's related to growing document sizes as people read along in a document. This happens because the page caching that makes the reader fast is causing the browser's memory load to keep increasing...

We are working on a general reader upgrade over the next few weeks, and I think that I will try to include a solution to this problem in that update.
