### ISSUE TITLE
Tizra Sites are down

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#26]
Internal server error.

Please send us a note describing what happened, and we'll try to get things fixed as soon as we can. Please send email with details on the steps leading to this error. We'll get back to you as soon as possible.

---

I attempted to refresh the page.
ASPPA and TRB. Haven't checked any other sites.

**Comment by orangedrink** [comment]
Ryan did you try refreshing the page? Try that.

**Comment by orangedrink** [comment]
I alternately get internal server error and the page cannot be displayed. Seems like the server is restarting over and over again?

**Comment by orangedrink** [comment]
I tried refreshing and it's still broke.

**Comment by orangedrink** [comment]
I fixed it. It worked after I clicked refresh.

**Comment by ghost** [comment]
Amazing.

**Comment by daviddurand** [comment]
This was a hosting problem at our end. We had a backup process that went awry and it took us a few minutes to get things going again because it was slowing down the system at the same time we were trying to fix it. We did a restart, and things are fine now.

The original problem was a noncritical problem with a nightly backup. Today, our normal process to terminate it caused a follow-on problem that we had not encountered before, and it took us a few minutes to get everything back online.

We are examining the details and will update our procedures so that this can't happen again.

**Comment by orangedrink** [comment]
Thank you David.
