### ISSUE TITLE
Links to documents on y90hub.sirweb.org showing document TOC when document is set to bypass toc

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#27]
This link takes me to the document TOC page when I believe it should be showing me page 1.
http://y90hub.sirweb.org/1vpbrv/
It's causing some problems with disqus commenting.

This is working as desired on our kc-lite site:
http://kc-lite.omnipress.com/1plush/

**Comment by daviddurand** [comment]
Thanks for this report, I found the document quickly.
there's a recent bug in metadata publishing (since last night) which is causing the problem -- the properties are not getting properly updated when you publish the documents.
I'll get a fix in place as soon as I can.
Once a fix is in place, republishing the documents with problems should be adequate. You will only need to use metadata-only publish, which is quite a bit faster.

**Comment by daviddurand** [comment]
A fix is implemented and tested. Not live yet.
