### ISSUE TITLE
User can only see pdf with left menu out

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#275]
I had a user today call me and when she goes to look at one of our books, she just sees white space in the middle of the screen. When she hits one of the menu buttons on the left, the help button for example, the document then shows when the menu is open. She's using IE, I told her to use Firefox for now, and I walked her through resetting her advanced settings, security settings, clearing all her cache and history and everything. I didn't know if there was maybe something I skipped over that y'all might have a better idea on what to check? Anything would help. Thanks a ton!

**Comment by daviddurand** [comment]
We support IE back to version 8 in the new reader, and fall back to the old
one for 7, but I can't be sure that there are no problems -- and IE has a
huge number of preferences that can affect things. If you can replicate the
problem in compatibility mode, you can see if the problem is related to any
customizations you have made to the reader by visiting the staging site
with customizations turned off… This sounds like CSS z-index problem -- IE
treats z-index a completely different way than the rest of the world.

If you can't track it down (and it's not IE6), send me the info and I'll
see if I can find something….

  -- David

On Tue, Aug 27, 2013 at 12:21 PM, Kuhrt Cowan notifications@github.comwrote:

> I had a user today call me and when she goes to look at one of our books,
> she just sees white space in the middle of the screen. When she hits one of
> the menu buttons on the left, the help button for example, the document
> then shows when the menu is open. She's using IE, I told her to use Firefox
> for now, and I walked her through resetting her advanced settings, security
> settings, clearing all her cache and history and everything. I didn't know
> if there was maybe something I skipped over that y'all might have a better
> idea on what to check? Anything would help. Thanks a ton!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Tizra/Tizra-Customer-Tracker/issues/275
> .

---

David G. Durand
CEO / CTO
Tizra
9 Catalpa Road
Providence, RI 02906

Email: david.durand@tizra.com
Phone: +1 401 935-5317
FAX: +1 401 273-5171
Web: http://www.tizra.com/
Blog: http://blog.tizra.com/

Online publishing unbound.

**Comment by Kuhrt** [comment]
Ok, you pretty much confirmed what I was already thinking. I'll let you know if we just can't get it. Thanks!
