### ISSUE TITLE
# sign in links

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#277]
I know that there are different commands you can add with the # sign in a link, but we have some links in our curriculum that has that has the anchor in it. When you click on those links it just sends you to a loading page on Tizra instead of going to the link. You can of course right click it and copy and paste it to the browser and it works fine, but many of our customers don't/won't do that. The link below is to an example of it. Is there any way to make it bypass those commands and go to links with the # sign in it? Thanks!

http://ccfcs.tizrapublisher.com/high_school_choices_explcars/5

**Comment by daviddurand** [comment]
This seems to be a markup generation problem. The link in question should have target="_self" and/or rel="external" on it, and it doesn't. The link address itself is correct... The problem is that jQuery mobile is processing the link as an "ajax navigation link", and since it's not even on the right domain, that is failing.

I'm investigating why the right link markup is not being generated. If you need a quick fix, add ',link-rel:external' to the end of the anchor in the PDF; that will fix the link for the time being. (The tizra fragment-id codes are deleted after taking effect, so the link itself will be unchanged when published to the site).

**Comment by Kuhrt** [comment]
Thanks so much for looking into this! The quick fix is working perfectly!

**Comment by daviddurand** [comment]
The fix is finally in place, so you need not add the link-rel to your fragment ids any more. This will go live for all documents published after tomorrow.
