### ISSUE TITLE
Forms no longer work in PDFs once they're downloaded

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#286]
For ai.tizrapublisher.com (knowledgecenter.appraisalinstitute.org), if a PDF is uploaded with forms enabled, the forms are disabled when the form is downloaded and users get this error message: 
![image006 2](https://f.cloud.github.com/assets/3876308/1290389/073f91ba-3030-11e3-8154-1bd0c38ee190.jpg)

Is there any way to make it so that forms are not disabled when the PDF is uploaded to the system?

**Comment by daviddurand** [comment]
We never supported use of forms in books, because there has always been an image-mode method of delivery. Image mode is now the preferred mode of delivery, as well.

This may be a new issue, perhaps due to updates to Adobe Reader and Acrobat. We have always extracted pages from the PDFs, so that has not changed. We have also always supported watermarks as well, but not every site enabled them. If you have made changes to watermarking policy, the Tizra watermarks could be affecting the reader.

There is a pretty easy workaround: simply deliver the forms as individual PDF files, rather than in the reader. Then they will be delivered as uploaded.

There are two ways that you can accomplish this (which are really just variants of each other). If the form itself is the complete document (and not a part of a much larger one), you can use a link to ~~PdfSource/0 to allow downloading of the original document as a whole (you need to make sure that "Allow source downloads" is set on your user's licenses, as we don't normally enable direct download of the source PDF. That URL could be used in markup to use the embedded viewer. Alternatively, you could generate a "form-only" PDF and upload it as an attachment (or a free attachment), and link to that from the main document.

If you are using the attachment approach, you may want to read about the download and link options in the Wiki.

https://github.com/Tizra/Tizra-Customer-Tracker/wiki/New-attachment-features

**Comment by aabercrombie** [comment]
I'm opening this issue again because the workaround isn't helping.

Once I'm on a PDF page (for example http://knowledgecenter.appraisalinstitute.org/829-student-handbook/1) and I click the download icon, which has the address ending in ~~PdfSource/0 (see photo below) I still get the forms error when I download the file. Based on what you said above, that shouldn't be happening. All licenses are set to allow source downloads.
![2014-02-07_0828](https://f.cloud.github.com/assets/3876308/2110547/069b4684-9005-11e3-98c4-d4c330917173.png)
Since that download link is going to the correct link to simply download the PDF, I don't understand why this would be happening.

**Comment by aabercrombie** [comment]
![2014-02-07_0838](https://f.cloud.github.com/assets/3876308/2110605/ab19ffca-9005-11e3-84cc-fab331563215.png)

**Comment by aabercrombie** [comment]
One more note: the downloaded files work in Adobe Pro, but not in Adobe Reader.

**Comment by daviddurand** [comment]
I'm confused as the ~~PdfSource/0 link is literally a link to the file itself, as uploaded to Tizra. We don't change anything in the file at all.

Browsers can sometimes lie about the content-type of a file (Mozilla and Firefox do this a lot, actually). And we sometimes have no choice but to believe them -- if the type is wrong that might be causing the browser to do something funny with the download. You can check the content-type in admin tools and change it, if it's not PDF.

The fact that tools are reacting differently might indicate a content-type problem.

Are these files passing through a browser plugin, or being downloaded directly? We've had some recent reports of funny behavior of PDF attachments in the Crome plugin, so that could be an issue; we haven't yet had time to track this down, so we're not sure if it's just a Chrome bug, or something we are doing. 

Does the results vary if you download the file from the link in the admin instead of through the browser? I believe the admin link always does a direct download.

**Comment by aabercrombie** [comment]
If I do a direct download from the admin side, then I can open the file and use the form. It looks like in both Firefox and Chrome it's passing through a browser plugin (opening in a new tab in the browser and then you have to click download again from there to pull the file down to your computer). If that's the issue, then is there a way to force that to just download directly without the intermediate browser plug in step?

The content type listed in the document-content field is a pdf, so that shouldn't have anything to do with it...

**Comment by aabercrombie** [comment]
Hey guys, just checking in on if there's an answer for this?

**Comment by daviddurand** [comment]
So, One thing I said above was wrong. You have watermarking turned on for the site, so there is watermark text being added. I think this is the problem....

Now, in Chrome, the file loaded -- and chrome was happy to let me type in the form, but acrobat reader was not.

If you turn off watermarking in the advanced site settings, that should fix it.

Sorry I didn't notice this earlier.

**Comment by aabercrombie** [comment]
Interesting. I'll let you know how that goes. If that's the issue, I'll close the ticket :)

**Comment by daviddurand** [comment]
Again, I'm really sorry for having been obtuse on this one, if it's that simple.

**Comment by aabercrombie** [comment]
It looks like that worked! I tested it in Firefox and Chrome and did downloads from both and the forms came through just fine. Thanks for finally figuring that out.
