### ISSUE TITLE
PDFs not downloading

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#288]
On ai.tizrapublisher.com, when you're on the PDF viewer and click on the disc image to download a PDF, it now merely opens another tab with the PDF viewer in it again instead of downloading the file. The URL is pointing to the PDF, so it should download instead of opening a new tab with the reader.

![2013-10-11_0956](https://f.cloud.github.com/assets/3876308/1315347/8429dcce-3285-11e3-9e26-bcbde02e97f7.png)

**Comment by daviddurand** [comment]
The new window is set in the markup that you have included in your design (`target="_blank"`).  View source will show that, and the markup in question is not generated by Tizra. In fact you can see in HTML source that the markup is from a FreeHTML block.

As to the in-browser display, it probably depends on your browser. I checked, and not only does it download in Chrome, but we are setting the `Content-Disposition: attachment` header to indicate that it is a download.

You will have to change the markup for the download button, and there's not much more I can do about the browser problem, though I suspect that it may revert to downloading once you remove the `target="_blank"` from the HTML.

![2013-10-11 12 42 02 pm](https://f.cloud.github.com/assets/1316941/1316333/586b0a36-3294-11e3-994e-ddfd9a08aacf.png)

**Comment by aabercrombie** [comment]
David, that doesn't make any sense. If it has to do with the link, why would that work yesterday and not today? We have the exact same setup on all our other sites and this isn't happening. I've tested it out on three other sites and the downloads work. It's only on AI that it's opening another PDF viewer instead of downloading the file. The issue isn't that it creates a new tab, the issue is that the PDF isn't downloading. Does that make any sense?

![2013-10-11_1201](https://f.cloud.github.com/assets/3876308/1316461/f8a7e9d6-3296-11e3-9c7e-7aeb2103838c.png)

**Comment by daviddurand** [comment]
I can clook at the markup that is being delivered, and where it comes from. It's from HTML that is typed into your site design. I can't change that, as it's your design. Similarly, I can check the HTTP headers, and see that they are set correctly (on that site) and that the files are being  downloaded (at least in my browser, but as expected because the headers are correct).

Once you have corrected the site markup, if it's still not working as you expect it should, give me the browsers and versions where it does not work. If those browsers are receiving the headers correctly, however, there may be nothing I can do do about it.

The design appears to have been updated on October 2.
