### ISSUE TITLE
Customers having some issues loading our content

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#289]
I've had several calls yesterday and today with people not able to see our content and some not able to open attachments. All of the issues seem to be coming from users using IE 8 or IE9. It basically says, windows does not know which program to open these files in, would you like to choose or choose for you thing. It does this when trying to actually view our curriculum and when they try to open downloaded power points or pdfs and things. I've been directing them to use Firefox or Chrome, but some have insisted on using IE. I can't seem to re-create the issue and have tried multiple things to get it fixed. I've tried restoring advanced settings, accepting the right cookies, clearing and deleting all browser history and cache, resetting IE completely and none of these get it to work. Any help would be great! Thanks!

**Comment by Kuhrt** [comment]
Sorry, forgot to say it never actually opens up anything after you tell it one way or another. That's the issue with it.

**Comment by Kuhrt** [comment]
Just got a call from one of the school districts IT guys that said when the files are downloaded, it's adding a 1 to the file extensions. So .pdf turns into .pdf[1] and then of course windows doesn't know what to do with that. I don't know if that helps, but thought I'd relay the message!

**Comment by daviddurand** [comment]
But it's only happening with IE... 

These are all attachments, right? no excerpt downloads?

**Comment by Kuhrt** [comment]
Yes, only IE. And I actually just finally re-created it with IE 9, it's the first time I got it to give me the error.

It's happening mainly with only the attachments. You can use this as an example http://ccfcs.tizrapublisher.com/brain_and_nervous_system/1 that first power point did it for me in IE 9.

Some people have reported not being able to see the pages at all, it automatically asks what program it wants to open with and then never opens up to even see the book.

**Comment by daviddurand** [comment]
Thanks Kurht, the specific filename was pretty helpful.

Some internal changes to ensure proper operation with unusual strings in URLs are causing the period in the filename to be URL-encoded in the `Content-Disposition:` header. This is confusing IE, and causing it to add "1"s to the filename. (This seems to be a general issue in some other cases:  [http://support.microsoft.com/default.aspx?scid=kb;en-us;325630&Product=ie]. Like many IE bugs the cause is hilarious, yet sad).

To be honest, I don't think that we should be using URL encoding in that header, and will make a fix.

**Comment by Kuhrt** [comment]
Haha gotta love bugs with IE. Thanks David!
