### ISSUE TITLE
Need an export of TRB user data

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#293]
I'm not having any luck with exporting the users from the TRB site. Is that something we should be able to do via the web interface or with so many users does it make more sense for you to do this for us manually?

**Comment by orangedrink** [comment]
Oh.. Looks like I got that working. I'll let you know if I have problems

**Comment by daviddurand** [comment]
let me know any details of your problems if you can replicate them. It could be some transient network stuff, if the files are big; and if the browser timed out or got interrupted while the system was building a huge download, that could cause trouble.

If there's a bug, we'd like to fix it.

**Comment by orangedrink** [comment]
Thanks David. I really appreciate your willingness to make this work.

When exporting all users  I'm seeing a stack trace coming out in the export at row 10563 column F. Please let me know what you can do to remedy that. Thanks!

**Comment by daviddurand** [comment]
Can you post the trace info?

**Comment by orangedrink** [comment]
Yes. I'll post that as soon as I can. Thanks!

**Comment by orangedrink** [comment]
```
<p class="t-error"><b>Method "public final java.lang.String com.cubchicken.personalization.model.UserData_$$_javassist_68.getCmsStringMetaTag(java.lang.String  java.lang.String)" threw an exception when invoked on com.cubchicken.personalization.model.UserData_$$_javassist_68 object "[toString() failed: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [com.cubchicken.personalization.model.UserData#131103276]]". See cause exception.           
```

**Comment by daviddurand** [comment]
I assume this is a tab-delimited export...

I'm guessing that there must be more of that stuff, including maybe some freemarker errors. I could really use all of that stuff to help track it down.

It looks like this is happening because the user list is changing while you are doing the export. It could be a cache problem, but I don't think so. That means that another export attempt might work, or might fail at a different place.

I think I can ensure that the export won't fall over at the missing users, but the extra error info would be very helpful.

**Comment by orangedrink** [comment]
I'll try to give you some steps to reproduce this. Do you have the "*.tizrapublisher.com" address of the site so I can log in to that?

**Comment by daviddurand** [comment]
just go to the "Settings" "Site name" to get other names for the site.
