### ISSUE TITLE
When I log out of a tizra site, I get a blank screen (although it DOES log me out)

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#294]
If I am logged into a Tizra site:
cbw.tizrapublisher.com
or
demo.tizra.com

I log in as an admin (or as a NON-admin user).

When I click log out here -- cbw.tizrapubisher.com -- I get a blank screen:
https://secure.agilepdf.com/logout/1qje1l/internal?callbackUrl=http%3A%2F%2Fcbw.tizrapublisher.com%2Fauthcallback%2F1qje1l%2Finternal%3Foperation%3Dlogout

Same from tizra demo site:
https://secure.agilepdf.com/logout/1ldau/internal?callbackUrl=http%3A%2F%2Fdemo.tizra.com%2Fauthcallback%2F1ldau%2Finternal%3Foperation%3Dlogout

I can click the back button and return to the page where I logged out and it still LOOKS as if I'm logged in, but I do not have admin access.

**Comment by daviddurand** [comment]
Found this. Will be in place tomorrow.

**Comment by aabercrombie** [comment]
I'm currently not able to log out at all. Just get the blank page and stay logged in.

**Comment by daviddurand** [comment]
The blank page is coming up because some new logging code is trying to figure out what account you are logged into, _after_ you have logged out, and your session has been destroyed. The blank page, however does not properly signal its end to the browser, so the browser progress indicator will keep on going.
