### ISSUE TITLE
Having issues with html attachments

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#295]
We've started adding several interactive materials for our teachers. They're all html pages with javascript, most have directories with css files and other things. Right now there's 3 different types we have and each one of them are having an issue when clicking the link from our pdf pages. If you copy the links and then paste them in the browser or refresh the page they work fine, but clicking the links doesn't work. Below I have links to each of them and the issues they're having.

Crossword puzzle:
http://ccfcs.tizrapublisher.com/sale_mark_ad_dept_pcaphs/1 - Account Crossword Puzzle link (only link on page)
This link keeps the same url in the browser address bar and pulls up a blank screen. When you refresh, it just refreshes the page of the pdf instead of the puzzle. If you right click and copy the link, paste it in the browser, it works fine. This attachment only has the one html page for everything it needs.

Drag and Drop:
http://ccfcs.tizrapublisher.com/sale_mark_ad_dept_pcaphs/5 - Sales, Marketing and Advertising Drag and Drop (1st link on page)
This link links to the right page but just has an "undefined" error. If you refresh the page, it does exactly what it's supposed to do. This attachment has an initial page that detects what device is being used and then serves the right page. It's a super basic and simple way to do device detection and if I need to change it I can, just thought it was weird that it works fine if you go directly to the link but not if you click the link from the pdf. This attachment has a full directory of images, scripts and css.

Matching game:
http://ccfcs.tizrapublisher.com/sale_mark_ad_dept_pcaphs/10 - Engineering Matching Game (first link on page)
This link loads the page but without the javascript and css in its directory. If you simply hit refresh or copy and paste the link, it works as it should. This one has a small directory with images and css files.

There's several of these in this one pdf and they all act exactly the same way. Thanks for any help you can give!

**Comment by daviddurand** [comment]
I found a javascript problem in the page initialization for the reader that was interfering with the link setup.

This was a bug at the Tizra end, but it's always a good idea to check the Javascript console, as problems there can cascade into other areas.

Also, I see that you are using full links to the attachments. It's probably better to use relative links so that you don't wire yourself down to a particular site layout more than you have to. So for:
`http://ccfcs.tizrapublisher.com/sale_mark_ad_dept_pcaphs/~~FreeAttachments/DepartmentsAccountingVocab/DepartmentsAccountingVocab.html`
you could just use:
`~~FreeAttachments/DepartmentsAccountingVocab/DepartmentsAccountingVocab.html`

The other thing I notice is that you are using the original reader. The new version, the so-called "Beta Reader", is now the best choice, so you might want to start testing with that version. There's info on the wiki:

https://github.com/Tizra/Tizra-Customer-Tracker/wiki/Reader-Beta

It may require some small markup and style updates, but the javascript code is cleaner and more reliable, and the underlying jquery mobile library has been updated, also improving platform support. There are also some more new features, including lightbox popups.
