### ISSUE TITLE
'Display Table of Contents?' setting not respected when document is found by full text search..

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#30]
Many of our documents use the document TOC page to display a short message that the author had not released the document to be shown on the site. This seems to work when searching by most criteria but when using the full text search I am granted access to the relevant page of the document.

To reproduce this:
1) From the site's home page do a search by paper number for paper 12-0062 
2) Click on the result for the paper (not the presentation)
3) You should see the desired behavior
4) Now from the home page do a full text search for the title of the same paper: From Meso-Scale Analysis to Micro-Scale Environments: Model-Based Approach to Select Case Sites for Conducting Walkability Audits 
5) Click one of the results for the paper (not the presentation)
6) You are taken directly to the document

This doesn't seem like the intended behavior to me but let me know if I'm incorrect.

**Comment by orangedrink** [comment]
The more I think about it the more I think this may be the intended behavior...

**Comment by adane** [comment]
Yup.  It's functioning as designed.  Contents of the paper are being made accessible via a sampling license on the collection "Three Page Preview," and possibly others.  Note that full text search hits leading to pages 1-3 take you to the contents of the paper, but a hit leading to page 5 takes you to access denied.

If you want to prevent access to the contents of these papers, probably the safest thing to do is arrange tagging such that they're not included in any collections with sampling licenses.

**Comment by daviddurand** [comment]
You can only get to the paper _if_ the pdf is present in the system. Suppress ToC does not suppress the content if it exists. On most of the sites I've seen, you've been taking advantage of the fact that there is a ToC page even if there is no PDF, which means that it's a great place to put a message like that. If you actually have content that you don't want people to see, you have to use the access control system to make it unavailable. For instance, you could have a true/false property (approvedForDelivery). All of the collections that you use for licenses would require approvedForDelivery:true. Since no collections that are accessible to the public or to members would include the papers with approvedForDelivery:false those searches would lead to the access denied page. You could use a macro on that page to display an appropriate message for those papers.

Or, as you have done on other sites, you could delete the PDF from those papers -- then the pages won't exist, and things will work as they have on other sites.
