### ISSUE TITLE
Random system sign outs

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#313]
I've gotten several support requests for two of our sites this week (elibrary.asppa.org and aga53756.tizrapublisher.com) that the system is randomly logging people out. We've had users say the system is signing them out after 5 mins on the site. After being kicked out, they also can't get back in because the browser is holding on to their log in information.

I had the same thing happen to me yesterday morning while on the back end of the system for ai.tizrapublisher.com. I changed the name of a file, hit save, and was kicked out. 

tkramer@bullardlaw.com <--- User with issues on ASPPA site
tdvoll@azuditor.gov <--- User with issues on AGA site

Why is this happening? It's not the usual half hour time out.

**Comment by daviddurand** [comment]
There were a few outages due to a java vm bug that randomly hit us. The
system does take 5 minutes to come completely back again when that happens
at peak load, because it ends overloaded as all those people log back in.

Ignoring late-night/early AM maintenance, this list gives you a sense of
restarts recently, which have been more frequent than usual due to this
problem.

A restart feels like a logout login problem because usually the only thing
that happens is a need to log in again, plus some real slowness for a few
minutes (if it's peak time for the east coast, and the texas schoolkids).

catalina_2014-01-30_08.14.20.out.gz
catalina_2014-01-28_11.51.53.out.gz
catalina_2014-01-26_19.16.50.out.gz
catalina_2014-01-26_14.03.02.out.gz
catalina_2014-01-24_16.54.43.out.gz

I'll look to see if there are any problems with those accounts.
