### ISSUE TITLE
ASPPA Emails

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#32]
Can I add in first name or last name into an email?

**Comment by daviddurand** [comment]
It seems to be missing from the documentation. I'm sorry. It's also missing from a few messages where it makes sense, so I'm adding it to them for tomorrow. (the user record got omitted because there were already properties for user information in place, but they are not complete).

The variable is **available** for user activity emails (`mail.newpassword`, `mail.accountupdate`, `mail.deletelicense`, `mail.usercreate`, `mail.addlicense` ). The useful values are the properties of the user:

For every "propertyName" `${user.props.propertyName}` will give the value of that property on the user.

The user's first and last name are the predefined properties FirstName and LastName. So, for instance `${user.props.FirstName}` gives the first name of a user.

I'm adding it now to `mail.activatedaccount`, `mail.packagepurchase`, `mail.activationcheck`. These are currently **not available** and won't be in place before tomorrow. I'm also going to add `${user.email}` because it makes sense.

**Comment by ghost** [comment]
when i try to add `${user.props.FirstName}` into an email the email no longer sends.

I'm currently working on getting `mail.activationcheck` done for asppa.
It works without it, but not with it.

**Comment by daviddurand** [comment]
This sounds right, as mail.activationcheck is one of the emails that does not have the user variable in place.

You should check out the freemarker manual at some point to see the stuff you can do, but one safe way to refer to a variable is to use the ! operator to set a default in case there is a missing value:

`${(user.Firstname)!"no name"}` for instance, will never cause the email to fail, and will show a missing name as no name"
`${(user.Firstname)!""}` will just skip it, if there is a missing value (substitute in the empty string).

**Comment by ghost** [comment]
Thank you David.

I also noticed that in the email () the url ${site.homepage}/~userOrderHistory doesn't seem to work. 
It comes through in the email as http://elibrary.asppa.org/~userOrderHistory, but the only way I can get a page other than the home page to load is to go to http://elibrary.asppa.org/1v3ibr/~userOrderHistory.

I'm not really sure how to edit this.

**Comment by daviddurand** [comment]
You can't put the user order history in the email at the moment, at least the way you want.

~userOrderHistory works if the user is already logged in -- otherwise it's a security problem. Clicking on an email link, the user is most likely _not_ logged in. 1v3ibr is the identifier for your account (or whatever account you were using for testing). The normal order history link is constructed on a per-user basis.

You can get access to the 1v3ibr component using the "user" variable. try a url like this:

```
 ${site.homepage}/${user.urlId}/~userOrderHistory
```

The way the order history page is written, it must get an identifier for an account (unlike some of the other account pages).
Frankly, the current set of account pages is way too complicated, and I'd recommend putting the order history, or even better, the license block on the ~userInfo page, and just skipping the special page.

 I suggest the user info block because the order history is supposed to be about purchases, and not current licenses, although it does seem to show some licenses. 

I'm willing to look into potential bugs (there probably are some, because almost no-one uses all those page templates), but I'm not sure if it's worth doing, as I'm likely to want to simplify the whole thing at a later point. Let me know if this gives you enough to make progress.

**Comment by ghost** [comment]
Thanks for the Info David.
Just an FYI. The default email for mail.addlicense has ${site.homepage}/~userOrderHistory in it. I'm guessing you would probably want to change that for all future setups with emails exposed.

I needed to know if we set something up wrong, but couldn't find anything. I don't know if Order History will be important for ASPPA, so I just switched it to ${site.homepage}/~userInfo and it seems to work.

**Comment by daviddurand** [comment]
Thanks. Clearly an old bug. We'll fix it.

**Comment by daviddurand** [comment]
You can put the the order history block into the User Info page if you
want, or even create a static page for it.

---

David G. Durand
CEO / CTO
Tizra
9 Catalpa Road
Providence, RI 02906

Email: david.durand@tizra.com
Phone: +1 401 935-5317
FAX: +1 401 273-5171
Web: http://www.tizra.com/
Blog: http://blog.tizra.com/

Online publishing unbound.

On Thu, Feb 23, 2012 at 10:54 AM, Ryan Hood
reply@reply.github.com
wrote:

**Comment by daviddurand** [comment]
default email link now directs to ~userInfo
