### ISSUE TITLE
Forgot password issue

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#381]
Our forgot password system doesn't work. It sends a new password and everything but the new password it gives doesn't work when you try to use it to log in. This isn't that pressing, but it's just seemed to come up a little more often recently. I'm not sure if there's a setting I need to change or have messed up, but it just doesn't seem to do what it's supposed to.

**Comment by daviddurand** [comment]
Kuhrt,
The new password setting mechanism uses the registration/set password page on the final step. Your site is currently set up not to show the registration block needed for the final step. I think that your old design didn't even show the change password option. I've updated the staging design so that you can use it as a starting point.

You can test the password reset on staging. To see the registration page for a logged out user, you'll have to actually publish the design to the live site, since you have to be logged into _some_ account to get access to staging.

I added an HTML block with conditional markup:

```
[#if users?size > 0]
<style>
   #content {display:none;}
   #registration {display: block;}
   #already-logged-in {display: block;}
</style>
[#else]
<style>
   #content {display: block;}
   #registration {display: none;}
   #already-logged-in {display: none;}
</style>
[/#if]
```

This depends on the id being set for the registration block, and on whatever alternate text you want to display for a logged-in user. I just these in a way that seemed to fit with your design.

Checking that there is a logged-in user works because the reset form logs the user in if the reset link is valid, and the registration block _is_ the set password block if someone is logged in.  Reset links are good for 24 hours after a reset request, but can only be used once. This eliminates the problems teachers had with resetting their password several times, and not always having the right one when they went to log back in.

**Comment by Kuhrt** [comment]
Ah I gotcha, this is perfect! Thanks for helping me understand this! Working like a charm!
