### ISSUE TITLE
Limit Zooming

### ISSUE THREAD

**Issue by GWPublisher** [Tizra/Tizra-Customer-Tracker#388]
Say the total levels we have to zoom in/out on the text are as follows:
Zoomed out all the way: 0   zoomed out a little: 1   regular view: 2     zoomed in a little: 3      zoomed in all the way: 4 

Every time you push the + zoom in button, it will add one count to the number even though it won’t visibly zoom in any more.  For instance, if you were on level 4 and hit the + button 3 more times trying to make it zoom in more, the count is zoom level 7 even though you only see zoom level 4. You will need to hit the – zoom out button at least 4 times before you’ll see the page zoom back out.

Try hitting the - zoom out button several times; the text should eventually begin to shrink. 

Issue happens on all browsers.

**Comment by adane** [comment]
We're aware of this issue and looking into ways of fixing it, or at least making what's happening clearer to the user.

**Comment by GWPublisher** [comment]
Is there any new information on this?

**Comment by daviddurand** [comment]
We have an approach in implementation at this point. The new system will allow specification of a finite number of zoom levels, changed by the `+` and `-` buttons.

The buttons will be disabled if no further zoom levels are available in that direction -- preventing the the current "invisible zoom levels".

This is being implemented as a design parameter (rather than just a site-level setting), enabling it to be staged before deployment, and also enabling the exact zoom levels to be overridden on a per-publication basis. _The details of this overriding process apply to all design parameters, and documentation about how it works is in process, and will be placed on the developer wiki_

**Comment by daviddurand** [comment]
**closing ancient/fixed bugs**
