### ISSUE TITLE
RSS feed not working in specific browsers

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#393]
RSS feeds -- ex. http://publications.arl.org/all_complete_documents/~rss -- work in Firefox only (on Windows 8 and Windows 10), but fail in Chrome and and IE (on Windows 8) and Microsoft Edge (on Windows 10) and in Safari (on an iPad). Tested on ARL and Lab-Aids sites; 

Please see 2 attached screen shots:
rss_error_chrome (windows10)
rss_error_edge_windows10

![rss_error_edge_windows10](https://cloud.githubusercontent.com/assets/2480073/9552999/33b4865a-4d8a-11e5-99a8-8760eb8daa46.jpg)

![rss_error_chrome](https://cloud.githubusercontent.com/assets/2480073/9552901/7b336042-4d89-11e5-91ee-374f1dad4e83.jpg)

**Comment by daviddurand** [comment]
This seems to be due to the general dropping of direct RSS support in browsers, and not something we are doing at our end. This can be solved by means of RSS Browser plugins, that replace the features that the browsers are now eliminating.

Chrome and Safari share a lot of infrastructure, and seem similar in this way as well.

It's not something we can fix, because the relevant browser feature no longer exists:
https://productforums.google.com/forum/#!topic/chrome/LfDx3j4uYXw
http://stackoverflow.com/questions/1656574/google-chrome-rendering-xml-as-text-for-rss-feed
https://code.google.com/p/chromium/issues/detail?id=84
