### ISSUE TITLE
Saving + Publishing to staging a collection

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#410]
Has something changed that I can't update collections without the update immediately going to the live site?

I'm trying to update http://aga.conferencespot.org/ and everytime I edit a collection and save (or publish > staging) the change goes live. 

How do I stage updates now?

**Comment by daviddurand** [comment]
The definition of what is in a collection is always the same on staging, live, and content management. The collection definition has always been uniform across sites. While collections' contents are often different on staging and live because of differing metadata and publication status, that's because the same definition may be matching different things.

Collections originally shared the intro text in this same way (collection names are still shared like this). While the Intro Text problem was not happening on my test machine, it was happening on the live server for at least some collections, as you indicated. I've fixed this now. Some republishing may be needed to get the metadata in shape.

The two things that publish does for collections are to:
(potentially) make the collection visible to users;
set the metadata properties on the collection (ie. it's visibility properties, Intro text, Tags, etc.)

If the collection is used for a license, and you need to update the collection content definition for a new year, you may well have to create a new collection, if editing the old one will create a problem for access control.

**Comment by ghost** [comment]
Thanks. Does the same apply for properties? I had made a color change in properties meant only for staging and it updated on live too.
