### ISSUE TITLE
If statement working inconsistently between layouts

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#412]
I'm curious why the following if statement would work correctly on a collection page and the document toc page, but doesn't seem to work in the Title Content page.

`%IF_CONTEXT_VALUE_BEGIN(METADATA_VALUE:studyguidenumber,study12016)%
# study1Sections2016 {display:block;}

%IF_CONTEXT_VALUE_END%`

We set this up so that we would get different sidebar data based on what book you were navigating through, but doesn't work on the Title Content page. I tried to just pull the metadata onto the page using the following code
`%TAG_VALUE_OBJECT(studyguidenumber,)%`
The correct value is shown so I'm a little confused on why the if statement isn't working.

**Comment by ghost** [comment]
Anyone?

**Comment by ghost** [comment]
Any ideas on why this macro isn't working on all page types?

**Comment by daviddurand** [comment]
Sorry not to have jumped on this sooner.

I think what is happening is that the %IF is testing the metadata on the page itself, but the page metadata for pages is indexed for content search but isn't actually stored in the page. The property value macro automatically looks to the parent object (the Book)for any undefined properties, and so the value is showing up.

I'm looking into a fix and perhaps a quick workaround as well. Will follow up.

**Comment by daviddurand** [comment]
Could you post a site URL (staging would be fine), for some content where the macro is in place, but not working? I need to see the problem in context, to be sure. The %-macros are very finicky, so I'd also like to check for any syntax oddities that might be happening.

**Comment by ghost** [comment]
http://aga.conferencespot.org/sg1_Sec-I-2016/1

I ran a test where I just checked to see if I could get the study guide number metadata to show up using %TAG_VALUE_OBJECT(studyguidenumber,)% 
That worked for all of the title content pages, but as soon as I switched to the if statement it didn't register.

This was working at one point because I had the macros setup to navigate between chapters of the book, and all the sidebar information, but now all of that is blank.

**Comment by daviddurand** [comment]
Fix `%IF_CONTEXT_VALUE_BEGIN` will work on reader content pages, once the system is updated overnight. There is an alternative method that can be used today based on new freemarker template library functions:
New freemarker library functions:

```
 lib.currentPropValue(propertyName)
 lib.currentPropDefaultedValue(propertyName, default)
```

For instance:
`${(lib.currentPropValue('AdminTags')?join(', '))}`
will display the AdminTags values separated by commas (note that since
it's a keyword list, a freemarker list value is returned). If no
AdminTags field exists, a missing value is returned from the function,
and a substitution like this will insert the empty string.

If you want a special default value (on the pattern of the %-macros),
`lib.currentPropDefaultedValue`
makes that convenient:
`${lib.currentPropDefaultedValue('AdminTags', [])?join(', ')}`
or
`${lib.currentPropDefaultedValue('Title', 'No title')}`

Thus, a solution to the original problem is to use freemarker's more flexible
if statement (this is the long-term preferred approach):

```
[#if (lib.currentPropDefaultedValue('studyguidenumber', '') =
study12016')]
   ... whatever content ...
[/#if]
```

**Comment by ghost** [comment]
Thank you.

**Comment by ghost** [comment]
For the fix that you mentioned, will I need to republish anything? Not seeing any change to production today with the original macro.

**Comment by ghost** [comment]
%IF_CONTEXT_VALUE_BEGIN works, but %IF_CONTEXT_VALUE_EXISTS doesn't. -- Of course I didn't mention the second macro not working, I guess I assumed the problem was related and didn't realize I was using two different macros on the page

I'll try to figure out how to use freemarker templates. But the element doesn't have anywhere for me to add text, so I'm a little confused.

**Comment by daviddurand** [comment]
Sorry, this went live today inst4ead of yesterday.
Looking at the sidebar in:
http://aga.conferencespot.org/sg1_Sec-I-2016/
I see the proper CSS showing up now.

For the freemarker, you'd replace something like this:

```
%IF_CONTEXT_VALUE_BEGIN(METADATA_VALUE:studyguidenumber,study12016)%
    #study1Sections2016 {display:block;}
%IF_CONTEXT_VALUE_END%
```

with something like this:

```
[#if (lib.currentPropDefaultedValue('studyguidenumber', '') = study12016')]
    #study1Sections2016 {display:block;}
[/#if]
```

Freemarker [#if} can nest, which %-macros can't, and the "lib" functions can be used more places than just an if, _e.g._ to put the value inline you could use:

```
${(lib.currentPropDefaultedValue('studyguidenumber', '')}
```

On any page other than a reader page, you could use the this object directly:

```
${this.props.studyguidenumber}
```

Sadly in an if you'd have to use:

```
[#if ((this.props.studyguidenumber)!'') = study12016')]
    #study1Sections2016 {display:block;}
[/#if]
```

This is because freemarker throws an error for anything undefined, except if it's being substituted into content.

**Comment by ghost** [comment]
Yeah, the sidebar stuff is showing up fine. It is another set of controls that I had setup in 2012 that doesn't seem to work anymore. 

<div id="documentControls">
%IF_CONTEXT_VALUE_BEGIN(METADATA_EXISTS,previousSection)%
<p class="previousSection">%TAG_VALUE_OBJECT(previousSection,)%</p>
%IF_CONTEXT_VALUE_END%
%IF_CONTEXT_VALUE_BEGIN(METADATA_EXISTS,nextSection)%
<p class="nextSection">%TAG_VALUE_OBJECT(nextSection,)%</p>
%IF_CONTEXT_VALUE_END%
<div style="height:0;margin:0;padding:0;clear:both;"> </div>
</div>

Here is an example:

<div id="documentControls">
%IF_CONTEXT_VALUE_BEGIN(METADATA_EXISTS,previousSection)%
<p class="previousSection">%TAG_VALUE_OBJECT(previousSection,)%</p>
%IF_CONTEXT_VALUE_END%
%IF_CONTEXT_VALUE_BEGIN(METADATA_EXISTS,nextSection)%
<p class="nextSection">%TAG_VALUE_OBJECT(nextSection,)%</p>
%IF_CONTEXT_VALUE_END%
<div style="height:0;margin:0;padding:0;clear:both;"> </div>
</div>

What I'm trying to accomplish is controls between files. So each file has metadata that includes markup for the next or previous file. If it exists, it should show it, if not, nothing shows up. Apparently this hasn't been working for a long time and the customer never said anything.

I tried to use the freemarker example you provided in the free html block but I get [FREEMARKER]template error: Exception instead of what I'm expecting.

I thought I would need to put it into a freemarker template block, but that block doesn't have anywhere for me to put it. 

Thank you for your help.

**Comment by ghost** [comment]
If you want to look at everything I have setup, it is in the title content layout in the free html block titled Bibliography of the aga site
