### ISSUE TITLE
Site home page background disappearance.

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#417]
Hi,

I made some changes to the Contact Us section on ccfcs.tizrapublisher.com home page this morning. I tested them in staging, and everything looked fine. I published them live and tested them again. Again, everything was fine. About thirty minutes later I went back to our site, and the white background is no longer there, which makes the page hard on the eyes. I applied the previous version back to live so that I could look at my changes, but the previous version has the same issue. I have applied 4 or 5 versions from the library that worked fine before, and all of them have this issue too. Any ideas what could cause this? 

Thanks

**Comment by daviddurand** [comment]
I see a javascript error in your pages which seems to be indicative of the problem. My guess is that this is related to an update to the scriptaculous javascript libraries used by Tizra.

I looked at your design and the CCFCSscripts property contains scripts that are not using the jQuery noConflict wrapper.

If you look at the AppJs property, you can see the entire script is wrapped in this code:

```
jQuery.noConflict();
(function($) {
  ... code...
})(jQuery); 
```

If you put a similar wrapper around the code in CCFCSscripts that will solve the error, and hopefully the display problem as well.

I'll look at how the current code was actually working (which I would not have expected). However, you should change this in any case, as noConflict wrapping is a standard requirement for jQuery use outside the reader.

I'll close this ticket, but feel free to re-open if this does not fix the problem.

**Comment by ccfcs-ttu** [comment]
That seems to have solved it. Thanks!

**Comment by daviddurand** [comment]
I was looking at it, and I see a few other issues: you include two version of jQuery. One (1.9.1) is from the header, and is stored in a design parameter, while the other is included at the bottom of the page by an HTML block lower on the page (v1.11.1). The bottom of the page comes from the google servers which is good, and the version is obvious. I'd eliminate the reference to the design parameter version, as well as the parameter.

For one thing, that version is not minified, and its position in the header delays rendering until the file is loaded (though it will usually be cached)....

It's generally best to delay script loading as late as possible, so that browser rendering can begin immediately. Also to have all CSS in place in the header for the same reason.
