### ISSUE TITLE
library.smrp.org not loading in IE11

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#418]
I haven't noticed the issue in any other browser aside from IE11. In IE11 I get the following errors in console. It appears to be all related to scriptaculous scripts which I believe are standard scripts that Tizra loads.
HTML1300: Navigation occurred.
library.smrp.org
HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
library.smrp.org (1,1)
SCRIPT5009: 'Prototype' is undefined
effects.js (67,1)
SCRIPT438: Object doesn't support property or method 'isUndefined'
dragdrop.js (8,1)
SCRIPT5022: controls.js requires including script.aculo.us' effects.js library
controls.js (40,3)
SCRIPT5009: 'Class' is undefined
slider.js (16,1)
SCRIPT5009: 'Template' is undefined
sound.js (10,1)

When inspecting the blank page the following markup is all that appears for me:
`<html><head><script src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/builder.js" type="text/javascript"></script><script src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/effects.js" type="text/javascript"></script><script src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/dragdrop.js" type="text/javascript"></script><script src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/controls.js" type="text/javascript"></script><script src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/slider.js" type="text/javascript"></script><script src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/sound.js" type="text/javascript"></script></head><body></body></html>`

view source is even less helpful:
`<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/builder.js"></script><script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/effects.js"></script><script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/dragdrop.js"></script><script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/controls.js"></script><script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/slider.js"></script><script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/sound.js"></script>`

**Comment by daviddurand** [comment]
I can reproduce this, but I can't determine what is wrong exactly, except that it's in your customizations.

The entire page actually loads (and displays briefly, if things are running slowly). You have to use the Network tab to get IE's tools to show you the actual delivered content.

Quite quickly after that, some script deletes all the content from the DOM.

Tizra did make a change recently; we enabled deferred loading of the scriptaculous scripts (speeding page display), and moved them to the end of the page, which helps performance and should increase compatibility with jQuery. Since defer is supposed to work in IE11, and you use jQUery noConflict, and the scriptaculous scripts are not actually called on this page, none of this should be a problem.

I noticed that the site is still set to send the IE7 compatibility meta-tag to the browser, which probably is no longer a great idea (nor the IE6 compatibility scripts). Unsetting this option fixes the problem (it's in advanced site settings). For the moment, I have left it unset. This is a site specific problem as a vanilla site with the compatibility mode set does not have the problem.

I'd recommend leaving it off, and fixing any rendering problems by updating your CSS if necessary.
