### ISSUE TITLE
ASPPA Search Question

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#42]
The site is at http://elibrary.asppa.org/

We're a little confused about the search results being returned by the site. I think it may be a bug.
To reproduce what we're seeing:

1) Try a quick search for the term 'form'. You will see about 1500 results returned by the system.

2) Repeat the search with the same term but (using the select input under the quick search input) limit the search to the ERISA Outline Book or The Source.

3) You will see dramatically fewer results. When limiting my search by collection in this way I can find a total of 6 occurances of the term in the site (6 in The ERISA Outline and 0 in The Source) so naturally we are wondering what happened to the other results.

You should note that this is not the default quicksearch form but one that I recreated using a free HTML block. Let me know if I'm doing something wrong there.

Thank you!

**Comment by daviddurand** [comment]
I agree that it looks like there may be some problem with the search limit to collections. We are not seeing this across all sites in general. I have tried some spot re-publishing, and testing with the original block, and those have not affected it. I will continue to investigate.

**Comment by orangedrink** [comment]
We did republish all documents at one point and did see some small changes in the search results. I think we saw a few more results come up but still not as many as expected. 

I'm sorry, I don't remember how exactly the results were different or even what kind of search we were doing but thought this detail might at least help a little.

Thank you!

**Comment by daviddurand** [comment]
There was a nasty search indexing bug that was not indexing certain properties (like tags) on the individual page objects used for full text search -- so those pages were not showing as part of the collections on the site.

I fixed the problem today, and started republishing asppa (keeping the dates the same). It's already a lot better and it should be fine once the republishing finishes.

While I was at it, I found the cause of a problem that had been happening during large site updates. During the publication process users could get error pages because the search index might change between the start of a request and its completion.. With the new change, errors won't occur, rather, users will get results from whatever time they submitted the search, regardless of changes that happen during the processing of the request.
