### ISSUE TITLE
Some Items Missing from Search

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#422]
At least one of the items that used to appear in this search...

http://einsteinpapers.press.princeton.edu/~searchResults?searchMode=quick&searchText=wasserwellen&context=-2&sortField=Sort

...is no longer appearing.

**Comment by daviddurand** [comment]
Since I'm not sure what item was missing, I can't tell if this is still an issue. However, I believe that any remaining German search problems should be fixed at this point.

**Comment by daviddurand** [comment]
Accpding to this old email, the problem is fixed:

Here’s the search I do in demos…

http://einsteinpapers.press.princeton.edu/~searchResults?searchMode=quick&searchText=wasserwellen&context=-2&sortField=Sort

And here’s the page that used to come up (among the first couple of hits) that doesn’t anymore…

http://einsteinpapers.press.princeton.edu/vol6-doc/428?highlightText=wasserwellen
