### ISSUE TITLE
Slow/glitchy document scrolling

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#423]
As stated, after opening a document, or navigating to a new page in a document, it can take several seconds before we are able to scroll up and down the page. Even then the ability to scroll can be glitchy and keep freezing and unfreezing. We are not sure when this began, but it was first brought to our attention by a customer on Dec 28. Any ideas what could be causing this?

**Comment by ccfcs-ttu** [comment]
There also isn't a scroll bar on the right side of the screen. I have never used it, but according to customers, there used to be one that they used. The slow/glitchy scrolling seems to be gone now though.

**Comment by ccfcs-ttu** [comment]
This still isn't resolved. We have gotten numerous calls and emails from customers who are having issues with their ability to scroll through documents. We haven't made any changes to our site, so this doesn't seem like it would be something on our end. Again, any ideas?

**Comment by daviddurand** [comment]
Not sure about the performance issues. I'd need a lot more detail: browser, platform, document pages, any user actions, to know what exactly I'm looking for.

That said, I have brought back the scrollbars and cursor up/down based scrolling.

One potential cause of "glitchiness" could be the fact that you couldn't scroll when the cursor is over the next/previous page links -- this could be worse if people are moving to where the scroll bars used to be, as that would put their cursor right into the dead zone, as would leaving the mouse there, then trying to scroll.

For modern browsers that support the "wheel" event, I've made mouse wheel (non-click) scrolling work when the mouse is over other areas of the screen.

Startup delays can be due to any number of platform, network, or specific browser issues. We're not seeing them in general, so details will be important if there's a replicable problem in play.

I hope that the scroll fixes address the problems. If there's a replicable startup delay, open a new ticket. If the interaction still feels off, we can re-open this ticket.
