### ISSUE TITLE
Collection Intro Text

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#43]
If you republish a collection or it's metadata, the into text gets wrapped in a <p> that no longer shows up inside of the <p class="t-collection-intro" at the top of the collection page. This breaks any custom formatting done with css to t-collection-intro.

Also, when nothing is entered into the into text metadata field, the intro is still added to the page. This limits what can be customized with the text area on the page.

Let me know if I explained this well enough.

**Comment by daviddurand** [comment]
I see a few things happening here.

One is that the early tizra blocks assumed that some things would be just text, no HTML-- so for a collection description,
you have to enter unbalanced open and close tags if you want multiple paragraphs. if you want no paragraphs, you are out of luck (though you could suppress the built in description via style sheets.

Since we have sites that depend on how the blocks work, we can't easily fix this.

The workaround is either to use an HTML block, or an HTML property (if you need the text to be searchable). Either one can be put anywhere you want on the page, and the markup controlled.

Once we can take some of the work that's going into the new export and start to use it in the live site rendering improvements we've been talking about, we'll be able to upgrade the infrastructure for individual sites, rather than having to change everything at once.

**Comment by ghost** [comment]
Sounds good... 

So i'm guessing you can't just simple change the <p class="t-collection-intro"> to <div class="t-collection-intro">? 
That would fix the basic markup issue. But, I understand if that isn't possible because of other sites the need it to be a p rather than a div.

Thanks.

**Comment by ghost** [comment]
The missing markup in my response is:
So i'm guessing you can't just simple change the  <p class="t-collection-intro" to  <div class="t-collection-intro"?

**Comment by ghost** [comment]
I have a work around in mind that should work but I can't seem to figure out what the macro for the collection into text is. When you have the static output done, can you please tell me what it is?
Thanks

**Comment by daviddurand** [comment]
There isn't a macro for the collection description.  That's why I was suggesting an HTML block or an HTML property. The reason that you might want to use the property is if you want the text of the description to be searchable. Also, if you are going to a new design approach, the property would remove the need to override each collection's page template to put the description on it (which would be bad because of the burden it would impose on maintaining or redesigning the site).
