### ISSUE TITLE
503 - Potentially abusive access pattern detected.

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#436]
Receiving this message from Apache when I try to go to our site. Customers are experiencing the issue too. The message appeared this morning, so I gave it a little time. The issue seemed resolved, but I just received a call from a potential customer, and the issue is back. Is this an issue across the board or just for me?

**Comment by daviddurand** [comment]
This happens when something about access patterns indicates that a network host may be crawling the site or ignoring access control. The status expires after 10 minutes, though I can reset it manually. We have made some changes to the front end to enable https for all tizrapublisher.com sites, and this appears to be happening for some people, but perhaps only on the first access. I have made a change that I hope will fix things. If it still happens, let me know, and I'll disable the secure connections until we track down the problem.

**Comment by daviddurand** [comment]
I believe at this point we've tamed the excessive sensitivity of abuse detection. Feel free to re-open if this is not so.
