### ISSUE TITLE
ASPPA Document TOC questions

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#45]
ASPPA is telling us that their users are drowning in all the document TOC links. At the same time they do need them all. We have a plan to show and hide the various levels with javascript but would need to get rid of pagination on these pages for it to work well.

Would you be able to get us an estimate on what it would cost to remove pagination on doc toc pages for this site?

Alternatively we can just recreate the doc toc inside the abstract and show that on those pages but then we would have to do that work year after year so that's not the optimal solution for us. Do you have any other ideas?

Thanks! Let me know if you have any questions.

**Comment by daviddurand** [comment]
There have historically been performance issues with rendering very long TOC pages, so I don't think it would make sense to just "depaginate" the TOC pages. The overall performance story is once again where we like it to be, and I'd like to avoid taking risks there by starting to deliver large amounts of content we don't even want to display most of the time.

I agree that expanding TOCs are definitely a sensible approach in general, and probably better than linked pages, but real support for this seems like the way to go if we need to do it (rather than dumping 100K of bookmarks on the browser).

I  think that this is exactly the kind of place where providing JSon interfaces to the backend makes a lot more sense, and I think that ToCs and metadata would be a perfect place to start. Steve and Sean already have some proposals that we start some work on JSon interfaces. I think that a few Ajax-style callbacks would be the best way to get what you are really looking for.

There are also a number of features that you guys haven't used much that may be able to help with the problem.

The short TOC block has the ability to limit the levels of expansion, which might help. You can of course hide levels in the ToC editor, but it sounds like you don't want to do that.

 It could help a lot to use Excerpts to break the big documents up at smaller section levels -- Excerpt TOC pages only include the items within their scope -- which would make them shorter and more targeted.

You might also be able to combine these, using a limited-depth short TOC to link over to Excerpt TOC pages.

**Comment by orangedrink** [comment]
The short TOC would be a great quick solution. Can I put that on the document TOC pages ABOVE the full toc?

**Comment by daviddurand** [comment]
Yep, you could put it anywhere.
If you check the block parameters, you can control the depth as well...

**Comment by orangedrink** [comment]
Thanks David!
When I add this block to the doc TOC page I get:
FreeMarker template error!

Error on line 13, column 9 in com/cubchicken/plugin/title/model/PageBlockTitleAbbreviatedToc/html.ftl
renderContext.renderContent.pageNumberInSource is undefined.
It cannot be assigned to pageNum

What am I doing wrong?

**Comment by daviddurand** [comment]
I spoke too soon about putting it anywhere I guess -- I think we can fix this though.

**Comment by orangedrink** [comment]
Thanks! Any ETA on that? Of course they need this working ASAP..

**Comment by daviddurand** [comment]
Should be fixed now. May take up to 5 minutes for the template cache to expire the old version of the short ToC.

**Comment by orangedrink** [comment]
It works! Thanks again.
