### ISSUE TITLE
ASPPA Mobile Reader / PDF Reader

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#46]
The PDFs on an iPad seem to not render all of the text correctly. Is there any that we can do to improve this.

example page: http://elibrary.asppa.org/erisa-outline-book-chapter-12/9

First paragraph of the above page  is truncated. 
Also, the Bold text on the next page is blank.

**Comment by daviddurand** [comment]
This is almost certainly a PDF production problem. We use the built-in PDF renderer on the iPad, not the graphic renderer (which does have some more unusual problems). My guess is that there are some hidden font changes and that all fonts were not embedded, so that some of the text is not rendering.
Acrobat says that they are embedded, but also that font subsetting is in use -- that can often create problems.

On looking into it, there's definitely something odd going on. If you display just the PDF (not embedded in HTML), it works, even on the iPad. (you can verify this by adding .pdf to the end of the URL). It doesn't fail on the MacOS safari, which is pretty similar.

We don't do anything to the PDF display in the reader, and the failure doesn't look like an overlaid element (and we don't overlay things over the PDF -- plus the placement of the vanishing text does not seem to be constant on every page, and the underlines do show up though the text does not.

I'm still looking into it.

**Comment by ghost** [comment]
I'll see if I can run a test with embedding fonts, but redoing the PDF typically wipes out our cross links, so It may take some time.

**Comment by daviddurand** [comment]
I'm not sure about the cross link problem, but at the Tizra end, there should not be any problem with PDF links... If there is, I'd like to know about it.

I did a lot of playing around on my iPad last night with the bad pages, and I was able to determine that there _is_ something funny happening with the PDF itself. If you scale it up and down many times, you can see little white patches, (even in the plain PDF with no markup) -- these patches don't always happen at the same size, and seem to depend on the history of growing/shrinking the pdf as you view it. So while the reader display is more consistent, that is probably an artifact of how the browser happens to scale the PDF.

I was also able to change size and overlap of the white areas in the reader by shrinking and expanding the image in the areas that were having trouble.

The insides of the PDFs were definitely odd -- the text was compacted into a single object, and not inline like it is in most PDFS. That object looked like it was some encapsulated (and separately compressed) postscript code. It also looked like it might have been created by wordperfect still? (Because it refers to Corel).

All in all, after poking around, I don't think it's a simple font-encoding problem like I suggested. It could still be font-related of course, and it might be worth doing some tests with another variant of Times (if that's acceptable to the client) in case the particular font files that you are using might be really old, have become corrupted in some subtle way.

I tend to think though, that the Corel output may be using PDF in a way that most programs don't. We've seen that PDF has a lot a potential "funny" variations, that can cause a variety of problems.

What is the exact production process for this? Perhaps there are some changes we can make that will remove the issue.

I think it would be worth making a short test file and putting it on staging, so that we can quickly iterate through some tests without affecting the live site.

**Comment by ghost** [comment]
the pdfs are originally created with wordperfect because that is what the author of this book uses. 
I don't know what else you need to know about workflow, but essentially the author puts everything together in wordperfect and sends us the PDFs and wordperfect files. Because all of his PDFs were bookmarked, we started with using those files for the upload and crosslinking.

I will try recreating the PDFs, but I don't know if I can change the text or the software because I believe the linking in all the PDFs are dependent on the space on the page they appear, and any text shift would be a nightmare for us.

**Comment by daviddurand** [comment]
Are you saying that the author creates the links himself in the PDF
_after_ creating the files? If so, that really ties our hands as it's
an almost unsupportable production process. I'm afraid all I remember
about the conversations on this over a year ago was that it was not a
great process, but the details are all flown.

If he is somehow making links in the PDF directly, that could be part
of the problem. I think Acrobat does have some "cleanup" features that
can normalize the inner formats without affecting the layouts. Some
PDF tools create their own unique little problems.

There are a lot of options in any PDF generator, and many of them can
affect the online performance of the final file -- most of the time
it's not a problem, but we may need to get more information on exactly
what he's doing (hopefully so that you can replicate it, and
experiment with whether there are any variations that help.

I have to say that the appearance of some of the fonts (like the bold
italics) does not leave me feeling very sure that he has an up-to-date
setup.

**Comment by ghost** [comment]
I think I have this figured out now.
I tested out "reprinting" the PDF with our default settings, and then re-importing all of the bookmarks and links so they show up correctly. When I did all of this the PDF looks fine on an iPad. 

I'm guessing there is something wrong with the PDF that the author supplies, but since we can fix it we can close this issue.
