### ISSUE TITLE
Table of Contents Editing Not Working

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#474]
In the Table of Contents tab in Document Properties when I click on a ToC heading to edit it, I don't get an editable field.  The entry just highlights and in some cases the text is replaced by ellipses.  Clicking again returns the heading to its previous state.

**Comment by daviddurand** [comment]
I can't replicate this. Perhaps some browser caching or weirdness. Re-open if you can reproduce...

**Comment by adane** [comment]
I'm still seeing it in Chrome (77.0.3865.90).  See screen recording...

https://www.dropbox.com/s/0z1wcvh129kvero/toc-editor.mov?dl=0

Not seeing the problem in the current version of Safari.

**Comment by agriffis** [comment]
I can see this also, on Chromium 77

The problem is that the input is too wide at 440px. If it's sized down to 435px then it fits. When it's larger, it wraps down to the next line which is hidden from view. There's also something similarly wrong with the styling of the controls on the end of the line.

**Comment by adane** [comment]
@daviddurand I think this is the issue we saw on SCC today.

**Comment by daviddurand** [comment]
At some point, I fixed this.
