### ISSUE TITLE
SDE Caching question

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#53]
I've replaced a few documents on the SDE site and they look just fine to me. The customer however is not seeing the changes.

I've had her clear her cache, try another browser and even use a co-workers computer and still she's seeing old versions of these documents. 

Seems like an issue on her end but I just wanted to check with you and see if you had any ideas about what could be wrong. Could this have anything to do with Amazon's EC2 service? Any other ideas about what could be causing the issue?

Thanks!

**Comment by adane** [comment]
Hi David--

As noted in email a minute ago...

I haven't been able to reproduce this on my end either, but did have a thought that might help.  Assuming the issue is some kind of caching that's being done on the user's network, it may help to change the URL for the document via the Custom  URL field.  This should force whatever's doing the caching to re-fetch the file.

IMPORTANT: Make sure the URLs you enter for each document are unique, or users will get error messages.

Does this help?

Abe

**Comment by orangedrink** [comment]
That's a really good work around! I'll give it a try. Thanks so much.

**Comment by daviddurand** [comment]
The most likely cause of this is a caching proxy server that is not expiring things properly. If this is an SDE customer, it may not be worth special effort, but if it's SDE themselves, it may be worth investigating.

There are a lot of tricky issues around proxies (and a lot of proxy server bugs as well), so we are still actively working on improving proxy support.

We could work with them to try to track down the problem.
