### ISSUE TITLE
Markup issue with search results

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#55]
In the search results, when the span "t-search-snippet" includes html markup there is a chance for the markup to get cut off and cause major display or usability issues. 

I figured this out by doing a search on ASPPAs site with no search text, just searching the ERISA Outline Book.
http://elibrary.asppa.org/erisa-outline-book-chapter-13b/~searchResults?searchMode=advanced&searchText=&context=66341143&searchParam-Volume=&searchParam-Chapter=

There may be other solutions, but I can only think of these two things:
1. Make sure any html markup within the "t-search-snippet" span gets closed properly within the span.
2. Remove any markup not created by your system within  the "t-search-snippet" span.

If you need me to demonstrate, video tape, or photograph the issue, let me know.
Thanks, Ryan

**Comment by SeanLawler** [comment]
Any ideas, David?

**Comment by daviddurand** [comment]
It's pretty tough to do something sensible with a random chunk of markup to make it safe -- you can try various things, but they all present serious drawbacks. Snippets are so short, that there's not really an structure in them to fix up, so it doesn't make sense to even open that can of worms.

 Our practical choices are to 1) remove markup from search snippets, or 2) can make tags visible as explicit text. There are arguments for both sides, but since this is very much an edge case right now, I'm going to pick whichever one causes the least disruption to the existing system, with a preference for removing tags (as that's less intrusive for users).

**Comment by ghost** [comment]
I would say just remove any markup that your system doesn't generate for the t-seearch-snippet area.

**Comment by daviddurand** [comment]
Update will go live by tomorrow. tags will be stripped.
