### ISSUE TITLE
dialog box goes off the page... can't save changes

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#56]
http://screencast.com/t/cZyGCKxbSo0

**Comment by ghost** [comment]
Sorry, the Subject should say "Can't save changes"

**Comment by daviddurand** [comment]
On many dialogs, you can resize big text fields with most modern browsers, so you both expand the editing area when convenient, as well as shrinking it to expose any hidden buttons.

The problem seems to be that we made a change a while ago to make dialogs "fixed", which makes it much easier to see status reports and not to lose track of the interface state. However, you used to be able to scroll dialogs into view and that doesn't work now because they are fixed.

I 'm putting this in the bug queue, but in the meantime you may have to use larger browser windows. How often is this presenting problems in practice?

**Comment by ghost** [comment]
This is a recurring problem for me while I work on creating a new template design, and update the previous one. 
I would say it happens 80% of the time. 

Sometimes I'm able to go into full screen mode and see the update and cancel buttons.

I can live with this for now, but I figured I would let you know about the bug.

**Comment by daviddurand** [comment]
OK, this is fixed now. If you don't see the fix, you may need to force-reload javascript (but it shouldn't be necessary).

The new behavior is to fix the dialog to the window if it fits nicely, else the window (and the dialog box) are scrollable, so you can get to any part you need to. This fix should also be good for other long dialog boxes, like the super-tagger, or multiple publishing errors when a list publish is being done.
