### ISSUE TITLE
Excluding All Tag(s) in Account set not behaving as anticipated

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#59]
I include a tag, click save, but the tag doesn't get excluded... See the screen grab to help explain.

http://screencast.com/t/D8wZJwQzUKbg

**Comment by daviddurand** [comment]
I need to know what site you are doing this on -- and the rest of the details of the group, etc. It could be a data indexing issue or publishing issue, but I can't tell.

**Comment by ghost** [comment]
The site is the Appraisal Institute. http://knowledgecenter.appraisalinstitute.org (s72244389.tizrapublisher.com)
I don't understand what details you need about the group. I wanted to create a account set that included anyone with out the tag member so that I could provide two different offers for content.

I may have changed how i'm doing this, I just wanted to point out the potential bug and see if it can be fixed, just in case we do need to create an account set that excludes a certain group of people.

**Comment by daviddurand** [comment]
At first I thought there was an known issue related to queries that contain only exclusions -- the search engine does not like those due to potentially uncontrolled search results, but there is definitely something else going on, which I am working now. I needed to know about the site, to make sure that I can replicate exactly what you are doing...

**Comment by ghost** [comment]
sounds good. Thanks.
Let me know if it needs to be tested on other sites.

**Comment by daviddurand** [comment]
No additional testing needed, this was a real bug, not a database content problem. I've got a fix that will be in place tonight. You were right; tag exclusions were being ignored.

It's not as bad as it sounds, however, since there are distinct mechanisms for checking user set membership and listing the members of a set, or listing the sets for a user (for optimization reasons). The bug was affecting the listing functions, but not the actual membership tests. The listing functions are basically only used for administration displays. So the displays were showing group memberships that did not reflect the way the groups were actually being used in access control and other functions.
