### ISSUE TITLE
AI Site not publishing correctly

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#60]
http://knowledgecenter.appraisalinstitute.org/

I can't get what I have in staging for the "Title Content" page to publish correctly, and I can't figure out why.

http://s72244389-preview.tizrapublisher.com/021-student-handbook/8

http://knowledgecenter.appraisalinstitute.org/021-student-handbook/8

I don't know what I might have done, but I need to get this figured out as quickly as possible.

Thanks

**Comment by daviddurand** [comment]
I just spent the last two hours on this. I determined quickly that it's not a publishing problem, but had to investigate because of markup anomalies. They turn out not to be related to the Tizra system, but to something weird you are doing in your scripts.

On the way, I fixed a number of scripting bugs (that were not the problem), and discovered that the page block bad size only occurs when the user is logged out -- logging in fixes the problem. (as an aside, on a failed login your javascripts change the javascript state to "logged in" state label on the button even if you are not logged in, but that does not fix the display issue, I think).

I thought that there might be some bug in the reader markup, but that was because the browser was showing me markup I didn't understand on the working versions of the page -- extra jpeg page images that don't belong in PDF page mode. Now that I've traced it down,  it turns out that the code that executes to make your stuff display correctly is this very weird thing:
    if(j('#pdf embed ,#pdf object').length) {
        //var filename = window.location+"";
        //alert(url.replace(/^(.+)\?.+$/,"$1")+".jpg");
        j('#pdf .bounds').prepend("<img id='pdf_image' src='"+url.replace(/^(.+)\?.+$/,"$1")+".jpg' alt='' />").find('#pdf_image').css('width',j('embed.t-pdfpage, object.t-pdfpage').attr('width')).css('height',j('embed.t-pdfpage, object.t-pdfpage').attr('height'));
    }
    j("#page-controls p.t-pagebox").wrapInner("<a id='goto' class='t-pagebox button' href='"+url.replace(/^(.+?)\/(\d+)/gi,'$1')+"' />").find("a").unwrap();

This loads the image form of the page, for a noticeable hit in bandwidth, I'm not sure why.

I can't really track this down for you further. If you strip out any customizations to the PDF block of the reader, I'd guess that you can fix the problem, as the reader normally just works. If you are trying to customize PDF page sizes, you can do it with style sheets much more easily.

**Comment by ghost** [comment]
Thanks. I'll have David F check it out when he is back to clean things up.

**Comment by orangedrink** [comment]
this seems to be the same issue as I've reported here:
https://github.com/Tizra/Tizra-Customer-Tracker/issues/68
