### ISSUE TITLE
Author Index on omniplayground's static export is not coming through.

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#66]
We've built an author index on this site using a static page with a layout override. Works perfectly on the web but comes out blank on the static output.

**Comment by daviddurand** [comment]
The zip files are now considerably larger! The fix is live, but you should do some testing, as it was a complicated beast -- which, in error, I had not planned for at the start. 

There are limitations because the existing indexes really were designed with a live server in mind -- for instance any page can have an index block, and if it does, that block will use the query string to link to other versions of the same page with a different configuration of the index. Obviously that whole approach won't work with the offline exports. Similarly, we used the same method of query strings to generate indexes on other properties. The static export does not currently have a way to request indexes on any other types of field.

I'll leave this open a bit longer as I would not be surprised if there are some bug reports.

**Comment by orangedrink** [comment]
I'll take a look and let you know what I can find.

Thanks!

**Comment by orangedrink** [comment]
The file structure has gotten pretty messy. Users are going to have a hard time knowing which file they need to open to view the export.

The author index link in the nav doesn't point to any of these new files. Like I said in the original post this is a static override. Are the only types of indices we will be able to do author and title? This could be a problem since we often use a separate field for author names with last name first.

We do have documents with author names in them but the new files in the static export have no content. 

As an aside the CSS doesn't seem to be coming through any more either.

**Comment by daviddurand** [comment]
I only seem to have mentiioned this in email and not this bug report, but, yes, you will only be able to do Author and Title indexes. If you use the %-macros you should be getting links to the indexes; links using query strings can't work because there is no server, and will just lead you back to the same page. I believe that this limitation may even have been in from the beginning...

In theory, I could generate other indexes, but there is no way for the system to know what indexes to generate, as there are only two macros. 

As to the clutter: I suppose we can add an index subdirectory for the indexes. Or you can stick the whole thing in a folder and make an alias to the index.html (which was what I thought you were going to do -- all the URLs are relative).

You'll have to wait a day or so before I can look at doing that.

If you are getting empty files, there's probably something going wrong in gathering all the data... quick check...  Yes, there's a missing file: fake-sponsor2.jpg... It needed to be unpublished and republished again. Now that that's fixed, you may find that a bunch of problems go away now when you retry the export. I was certainly getting indexes with content, and style sheets in my testing (and I did not touch those areas as far as I know). I will check into it later.

Unfortunately, I have to find the export errors, as they don't show up as the browser is downloading the file, and we don't have anywhere to send them.

**Comment by orangedrink** [comment]
OK thanks. You can ignore the part about CSS. That was my mistake.

**Comment by orangedrink** [comment]
Just let me know when you have the folder structure worked out.

**Comment by daviddurand** [comment]
It's done.

**Comment by orangedrink** [comment]
Thanks David. I'll take a look.

**Comment by orangedrink** [comment]
My comments are disappearing so I added a new issue and emailed you to be sure you got the message. Thank you David.
