### ISSUE TITLE
Unable to make changes to designs on live AI site

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#68]
To reproduce:

1) See staging site of AI. Notice text at top of left sidebar that says "Right click to change free html string "
2) Publish design from staging to live
3) Note lack of text at top of left sidebar on live site.

Thanks David!

**Comment by orangedrink** [comment]
This appears to be affecting all sites. Please address this soon!

**Comment by orangedrink** [comment]
Ryan also reported this issue separately. https://github.com/Tizra/Tizra-Customer-Tracker/issues/60

Other sites DON'T appear to be affected at this time.

**Comment by daviddurand** [comment]
Your site markup and configuration is really complex, and the previous problem ( #60 )
was due to markup problems on the site, and not a system bug. Though this set of symptoms seems different, I suspect that publishing is correct, and this is some kind of markup error, or perhaps a failure to save the staging area before applying it to the live site.

Please check to make sure that there are no absolute URLs or javascript problems, and that you are saving staging before applying it, etc. If you can narrow down the problem, to a system issue, then just reopen this ticket, and we can work it.

**Comment by daviddurand** [comment]
I found the block that is causing that right click string to show up.

It's there on the home page. I changed it, just to be sure, and that worked.

I also changed the editing name of the block, so that it should be easier for you to find.

In general, using those editing names makes it much easier to track a complex design, because you can tell what's going on in the HTML without having to open it.

**Comment by orangedrink** [comment]
I don't see it on the live site.

I also don't see any record of you publishing anything to live.

I'm not sure you're even reading the original post.

1) See staging site of AI. Notice text at top of left sidebar that says "This text is still not showing up. "
2) Publish design from staging to live
3) Note lack of text at top of left sidebar on live site.

**Comment by daviddurand** [comment]
Sorry, not trying to miss the point, but I did.

I don't generally publish stuff to live _unless_ I'm fixing an egregious problem. It's not my site.

FYI, there's an alternative way to see the bug that I'm using right now: save the design in the library, and then re-apply it to the staging site. This operation save and restore operation is also a good thing to try if there seems to be a problem with a design, as there can be problems with complex setups, and this basically rebuilds the design.

When I did that, the HTML block inside the master block indeed vanished. The configuration of master blocks is quite complex, and I'm not sure what's going on at this time.

I think that it's due to trying to place blocks in slots of of master blocks that are defined in saved the children of the master block.

So If you have a slot _X_ in a master block **a** , and you fill _X_ with another master block  **b** you can fill in the slots of **b**. But, if you redefine **a** so that every instance will contain an instance of block **b**, Then you will run into the bug when you try to save the whole layout. So that means that if you want to fill slots in dependably, you need to move them to outermost master block, if they are to be replicated across instances of the master block.

This is a bug thatmay be a bit awkward to work around, but it's unlikely to be fixed quickly -- it's at least 4 or 5 years old at this point (because this isn't something that we've messed with), and it _may_ have come up once before, if my memory serves me. Frankly I'd rather work on the next generation smart blocks given the effort it's likely to be.

Call me on the phone if you haven't quite got the workaround in mind as yet. It's hard to explain.

**Comment by orangedrink** [comment]
OK. Thanks David. I'll read over this and your email a few times to try to understand this and will call as a last resort.
