### ISSUE TITLE
Any possibility of adding JSONP interface?

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#69]
The JSON interface seems to work pretty well so far. Any chance we could also add a JSONP interface?

**Comment by daviddurand** [comment]
The chances are pretty low. I'm quite uncomfortable with implementing a protocol that is based on running the data in a javascript interpreter.

I don't see a reason that we would need it anyway, and I hope that we are moving to hosting everything on a single domain, rather than away from it (with the one exception of the access-control dance at the beginning of a session).

What's the use case for it?

**Comment by orangedrink** [comment]
We'd like to be able to pull some of this data into existing user sites (this could save you some time on SSO setup) 

We're also looking at integrating tizra content into native mobile apps using this interface.

**Comment by orangedrink** [comment]
And you shouldn't need to run a javascript interpreter on the server side afaik. We basically just need the data returned wrapped in a javascript function.

**Comment by daviddurand** [comment]
I'm still not sure yet why only JSONP will work. What cross-domain accesses are required? Native apps certainly shouldn't need to use browser javascript hacks, because they are not limited by browser security restrictions.

I know that there's no javascript required on the server, but the core of JSonP is to deliver data as code, because the browser security restrictions are less on scripts (a funny decision in itself). I really don't like that idea as it presents more avenues for javascript injection attacks, etc. I'm not even going to consider it unless there's a compelling need for this kind of cross-domain data fetching, and there isn't a workaround possible.

**Comment by orangedrink** [comment]
Our application platform uses a browser to provide compatibility with iphone and android.

I'm not sure there's a security issue here since the javascript is coming from your server. I could easily (and do) call javascript from other third party sources. I could be misunderstanding what your concerns are.

Making the data we keep in tizra more portable will have a lot of applications we can't even foresee right now. It would be a shame and I think a big mistake if you limited your own system this way.

**Comment by daviddurand** [comment]
The concerns are javascript injection attacks -- Data could be manipulated to cause arbitrary javascript to execute on someone's browser. Right now, most data comes from the publisher (but user information comes from anyone), and as we extend the JSon stuff we may be including more different kinds and sources of data, like user annotations, so that potential attack window will only get wider over time.

You haven't explained yet why it would be necessary, as JSonP is just JSon, wrapped to work around the some special cases of browser security that should not be a problem here, as you can host anything you want on the same server that is returning the JSon Information.

It's possible to avoid script injection attacks by careful data escaping, but it's easy to inadvertently create bugs in that kind of code -- search the web for "Javascript injection" and "SQL injection" to see how common it is.

The other problem is that JSONP unlike JSon presents an attractive target for Cross-Site request forgery javascript hacks, in ways that JSON doesn't. While we don't have a lot of sensitive data right now, we may in the future, and so I want to keep the security situation simple.

http://en.wikipedia.org/wiki/JSONP

http://stackoverflow.com/questions/613962/is-jsonp-safe-to-use
The first few stackoverflow comments are positive, but the third one has a clear explanation of the problems.

http://james.padolsey.com/javascript/cross-domain-requests-with-jsonp-safe/
This guy is looking at a slightly different use case, and comes down against JSONP as an option.

Again, if you can explain why you _must_ have pages hosted on another domain that perform JSon calls to the Tizra servers, I will consider it more seriously, but right now I still don't even have an argument for why I would want to give myself a new set of security issues to track forever more.

To repeat, Tizra's JSon data is fully accessible -- except to javascripts run from non-Tizra web pages. I still don't see why that case even matters, since you can put any page you want onto the Tizra server, with no additional issues coming up.

**Comment by orangedrink** [comment]
Our mobile application platform uses a browser to provide compatibility with iphone and android.

**Comment by daviddurand** [comment]
I understand that your application uses a browser. You've said it twice now. What I still don't understand is why that browser needs to JSonP rather than JSon. JSonP is only useful for the special case of cross-domain server accesses, and I still don't understand why cross-server accesses are required in your mobile world. If you can explain the underlying issue, and if there are no alternatives that work well, that's what I really need to know.

It's also possible that several upcoming features (like offline HTML5 browsing in Tizra, and support for more kinds of file formats), may also provide alternatives.

**Comment by orangedrink** [comment]
Cross domain requests are needed because our application platform isn't hosted on your domain.

**Comment by daviddurand** [comment]
Right, but you _could_ host the HTML on our domain. You might need some special features for offline caching, but those are on the way soon. Those are the kinds of things that I'm thinking might change the story in a way which makes more sense to me.

 Also, if you are not hosting the files on an external server, your application, ought to be able to turn off those security restrictions, at least for local files.

At the moment, I'm still not sure that we're looking to open up the JSon APIs to external sites -- at least the current JSon calls. And if we do, I'm not sure that JSonP is what we'd do, since web integrators can easily build a miniproxy to get the JSon they want in any case.

The JSon feature is intended primarily to improve the capabilities of Tizra-hosted sites, and I think we're more interested in expanding the capabilities of Tizra sites than facilitating the ability of external sites to create scripts to whack on our servers.

If you can describe what you are doing on the mobile end, I can see how that fits into our mobile strategy, or if there are any easy workarounds that can be done immediately. What toolkits are you using? What applications are you trying to create?

**Comment by daviddurand** [comment]
I found this:

http://simonmacdonald.blogspot.com/2011/12/on-third-day-of-phonegapping-getting.html

"Well your application would be pretty useless if you couldn't get data from a remote server now wouldn't it? Luckily since your PhoneGap application is running off of the file:// protocol it isn't limited by the same origin policy. This means we can request data using XmlHttpRequest from any domain.

I'm going to give you an example of searching for all tweets that mention PhoneGap that demonstrates this ability without the use of any extra JavaScript library like jQuery or Dojo."
