### ISSUE TITLE
Question: Properties and Macros

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#70]
Is it possible to use if/else macros with properties?

For example, is there a way to do this:
%IF_CONTEXT_VALUE_BEGIN(METADATA_EXISTS,%DESIGN_PARAM(Images-HomePage,)%)%

[style]
div.homepagephoto {display:block;}
[/style]

%IF_CONTEXT_VALUE_ELSE%

[style]
div.homepagephoto {display:none;}
[/style]

%IF_CONTEXT_VALUE_END%

I'm trying to figure out some easy ways for our project technicians to easily setup sites and minimize how many times they have to edit a master block. 
If they were able to remove the home image from properties, and have the block disappear, it would be easier.

If there isn't a way to do this, it isn't a big deal. Just wanted to ask.

**Comment by daviddurand** [comment]
Unfortunately that doesn't work. The macro stuff is pretty limited.

What condition exactly are you looking to check? I'm not sure that you are asking for a way to test for the existence of a property with the same name as the URL of an image ... which is what the code in question would do, if it worked.

**Comment by ghost** [comment]
What I want to check is if a property, in this case it would be a home page image, has a value, or if it is blank.
If the property is blank, I want to use some css to hide the div that includes the image.

Does that help make more sense of what I'm asking?

**Comment by daviddurand** [comment]
Yes, that's what I thought you really wanted. It seems the goal is to make it easy for production people to just fill stuff in to tailor things, rather than having them edit the master blocks and HTML directly. You can get a lot of mileage out of presentation properties (design parameters) even without conditionals, since CSS has such good visibility controls.
For instance, with markup like this:

```
<div id="logo" style="display: %DESIGN_PARAM(logo-visibility,block)%">
<img src="%DESIGN_PARAM(logo,)%">
</div>
```

If there is a logo, upload it into the logo design parameter. If there isn't change the parameter `logo-visibility` to `hidden`.

Alternatively you could make the default `display` value `block` instead, and then you'd have to change two things to put a graphic in place -- the default would be no graphic at all, with nothing to do.

In general, parameters are designed to be an easy way for production folks to change things without having to go into the block details.

**Comment by ghost** [comment]
That is close to what I'm looking for, but if they have to edit something in the properties, it probably would just work for them to edit the css page... neither one seems better than the other option.

Thanks for the idea though.

**Comment by ghost** [comment]
Is this closed because there is now a way to use macros with properties, or are you just cleaning this up and leaving it the way it is. Only trying to figure out if I can change our documentation on macros.
