### ISSUE TITLE
Error reporting page for SSO debugging

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#72]
In working with Rick to get the SSO working for AI he asked if I would request a special page who's url can be passed in the target parameter so that when testing the SSO we could see any important debugging information. even a success/fail message with a reason for failure would be helpful.

Let me know if you have questions.

Thanks!

**Comment by daviddurand** [comment]
This is one of the reasons that the normal process for SSO includes billable time.

There are a lot of things that can go wrong and building a debugging tool is something that I have not even thought about.

At one point during early testing on the SSO, I realized that I had to take out a lot of the useful information I was supplying on errors because it was a security problem. Currently, if debugging of SSO is turned on, all the information goes to secure server logs that are not available on the web -- and those messages are mixed in with other stuff. They're also not controlled that dynamically right now.

We could think about an estimate to define and implement some debugging features I suppose.

I think you guys are still paying for some of my time, and if we can schedule something interactive, that would probably make the most sense, as it's not likely to take too long to find any problems.

**Comment by orangedrink** [comment]
We already got the SSO working for AI. I don't think he's really going to need this debugging page but Rick seemed to think it would have been helpful while getting to this point. 

I told him I would ask about it so I did but I thought this idea would be more likely to be helpful to you in the future. I'll let you know if AI asks about this again. Otherwise don't worry about it.

**Comment by daviddurand** [comment]
That's fine. Basically I agree that it would be helpful, but at the moment the feature is my checking some private logs, and there are reasons that that's a bit hard to change.
