### ISSUE TITLE
Testing Site -- Can't do fake purchase

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#75]
http://omniplayground.tizrapublisher.com/

Have I set something up correctly?
When I go to the testing site to make sure the new design looks good through purchase, I get the following error.

"Tizra Error
Test fulfiller does not work on live sites."

To help see what I'm talking about go to http://s34062332-test.tizrapublisher.com/17aeg6/?offerControlledObjectId=41198853 and click "Buy now".

**Comment by daviddurand** [comment]
I can see what's happening -- the operation is getting redirected to the secure site -- which should not happen for the testing fulfiller. I will fix this tonight.

**Comment by daviddurand** [comment]
I've tested the fix on the live server just now, and it's working again. It was a collision of two security measures that collided -- the new one was a more aggressive redirection of potentially secure URLs to the secure server -- and the old one was a check to make sure that only access via the (protected) test site would be allowed to use the "fake" fulfiller, so that people could not make free purchases.

Thanks a lot! The clear bug report and URL made it really easy to dig into this (and it is a pretty obscure issue, so it made a big difference).
