### ISSUE TITLE
Static export contents are missing

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#83]
I'm trying to generate a static export of the live design on omniplayground and am getting a zip file with only one html file in it.

http://screencast.com/t/KyGBwpLnHz

To reproduce just go to http://omniplayground.tizrapublisher.com/admin/main Click on presentation and then on the CD-ROM button next to the live design.

Thanks David.

**Comment by daviddurand** [comment]
There seems to have been a reference to a nonexistent Design parameter by a %DESIGN_PARAM macro in the design.

I've made changes so that such references will no longer crash the export.

However, your author indexes are on a static page, and that does not work with the site export. As I said, you have to use the special index page template to get an index generated. You also need to use one of the system macros to link to those pages:

`%URL_AUTHOR_INDEX_ALL%`
`%URL_TITLE_INDEX_ALL%`
`%URL_AUTHOR_INDEX%`
`%URL_TITLE_INDEX%`
