### ISSUE TITLE
?zoomFactor url parameter doesn't seem to work properly

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#85]
We're using zoomFactor to display enlarged parts of posters in the tizra system. We have in the past used the zoomFactor=3 URL parameter but now this doesn't seem to be working properly. Click the links below to reproduce the problem.

This image is 1104 x 710
http://templates.tizrapublisher.com/233fuu/1.jpg

This one comes through as 1105 x 710
http://templates.tizrapublisher.com/233fuu/1.jpg?zoomFactor=3

Thanks.

**Comment by daviddurand** [comment]
The zoomFactor parameter is an internal feature, which is currently subject to change with the new reader.

zoomFactors greater than about 1.6 were never supported, and the only reason they worked was a bug in the size limitation (since an image can have any or all of a maximum width, maximum height, and a zoomFactor, calculating the actual image size after PDF conversion and then limiting it to a feasible value is actually a bit tricky).

The lack of this check was causing transient service outages as the system tried to allocate 100s  or 1000s of megabytes of memory on large image requests (Frequently TRB posters).  Depending on current load, memory demands, and so on, all server response would cease from 20 seconds  (sometimes up to a couple of minutes!) while the system tried to allocate space for the image, garbage collected a few times, tried again, aborted all or most other active web requests due to lasck of memory, and only at that point would the image request itself fail. I actually spent quite some time puzzling over how I was generating zoomFactors of 3, as they were never legal.

If you want partial views of images, that is something that we could look at as an extension. There's no question, particularly for posters, that just removing or slightly changing the image size restrictions do what you want, as the intermediate images are just too large

Post to this issue if you want me to estimate the work for a partial image feature (or let you know if I end up having to create one for other reasons).

I believe that the current maximum size is set based on the total pixel count for an 8.5x11 page at 150PPI or 180 PPI.

Some adjustments in this might be possible at some point, but it sounds like only way to implement that kind of a zoom is for the server to generate partial, zoomed-in images. There is some chance that something like this will happen at some point in the evolution of the new reader, but it's not part of the plan at this point.

On the positive side, some of those posters were so large that they never displayed before, and at least now you can get an overview of the content instead of a server error...

I think for large posters a better option might be to put a conspicuous PDF download link on the page, and leave the image at its "relatively small" maximum size.

**Comment by orangedrink** [comment]
This has broken an important feature that we've already developed. The best solution for us would be for zoomfactor to work again as it did when I developed the poster viewing feature. 

This URL parameter was documented in the "Sampling Frames" wiki and no limit was ever specified.

**Comment by daviddurand** [comment]
David, I'm sorry about this, but you are going to have to do something different. If you don't want to use PDF or something like that, and want to continue to have some kind of zoomed viewer, we will have to build proper server side support for partial image delivery, and then you will have to rewrite your browser code to that new interface. It might not be very expensive to do the server work, but it will cost something, and it will definitely take your time.

 If the compressed images of posters are actually small once they are generated, you might be able to store them on the server as attachments, and use the attachments in your existing zoom reader.

I'm sorry if the sampling frame doc misled you, but sampling frames are about embedding a "small size" image into an embedded frame on an external website. It's not about creating enormous images for panning in a browser. I'm sorry that the restriction was not documented, but it's a restriction based on limiting the size of images delivered to a browser to sizes that can actually be effectively processed in the browser. I can't document all possible limits, and the current limits are based on pretty obvious sanity checks to avoid server performance problems.

When you are planning on investing a lot of time to implement a feature like this, it would be good to keep me posted, or check in advance, because not everything that seems to work actually does.

I simply can't revert the change, because the old code really doen't work. And the larger the poster, (and the more you would want your feature to work), the more unreasonable the server load, and the less likely it would work. Also, these accesses were causing (transient) server outages for all Tizra customers.

The resulting images are simply too large to process effectively, and final size of the file does not affect the memory required to render the page at all.

Just doing a quick, "back of an envelope" estimate, an image of 4000x4000 pixels has 16 million pixels. These are stored in memory at 4 or more bytes per pixel, for 64MB per image. During processing, we need to make at least one duplicate image for cropping purposes. That's 128MB of memory just for the image buffers to respond to that request. (and there may be additional buffers inside the licensed PDF rendering code that I'm not able to track).

It's not remotely sane to support individual web requests with those kinds of resource requirements. I saw some 4k x 4k poster image requests in the past -- the time to first delivery was between 30 seconds and two minutes. You could actually miss this performance impact in testing, if you kept using the same small number of pages, because we cache image results.  Subsequent deliveries would be much faster once there was one successful request. So it really wasn't working that well when it was "working," at least not for the poor sod who looked at the image first. And if they refreshed a few times because "the system was slow," they could ensure the image would not be successfully generated, and also cause errors for all other users on the server).

For the TRB posters, significantly larger sizes than that were often requested. And remember that this memory consumption goes up as the square of the resolution, so doubling the resolution multiplies the memory requirements by 4.  So a request for an 8000x8000 image (which might still work at low load) would take a half a gigabyte of memory to complete. Those requests are also going to be slow to complete, not just because of the memory needed, but because that memory then needs to be analyzed and compressed to create the JPEG.

Because the posters tend to have a different shape than pages, the way I'm limiting sizes may not be optimal (I think I prefer to limit width over height, for instance. So I may be able to tune the limits a little bit to get slightly larger maximum size images for posters, but these potential adjustments of perhaps 10-20% are not what you seem to be talking about.

**Comment by orangedrink** [comment]
That all makes sense. 

The attachments workaround sounds like a good idea. I'll go with something like that for now. 

If we started selling a few more of these would it be possible to generate the larger image at publish? It wouldn't have to be huge. Just readable.

Thanks.
