### ISSUE TITLE
Author Index on omniplayground's static export is not coming through. Some links to AI are broken.

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#90]
I'm having some trouble with the author and title indices. All of the files inside the index folder are 24KB and none of them seem to have any content aside from the banner/nav the sidebar and footer
http://screencast.com/t/6aM5MVPXN

I'm also having trouble with the links generated by the %URL_AUTHOR_INDEX% macro. On the home page and the pages inside the index folder the links look like "&lt;a href="index/index-Authors-ALL.html">Author Index</a>" which works but on other pages I get mixed results. On the Presentation index I get "&lt;a href="../collections/2011-presentation-index-Authors-ALL.html">Author Index</a>" Where the link is pointing to the collections folder instead of the index folder. On the photo gallery page I get "&lt;a href="../-Authors-ALL.html">Author Index</a>" which points to the parent directory where index.html lives.

Thanks.

**Comment by daviddurand** [comment]
some of this may be because of the image problem -- with part of the export crashing, it may create other issues.

It's also possible that your index blocks are different from what is expected -- with the limitations imposed by the filesystem, a lot of the things you can do on the site are more limited -- I'll take a look once I finish writing up the image problem.

**Comment by orangedrink** [comment]
That seems likely. When you have a chance let me know what my index blocks should look like and where they should go.

Thanks

**Comment by daviddurand** [comment]
We're really sorry about this. There have been a lot of infrastructure changes under the hood this week, and the author index stuff has definitely gotten broken in the shuffle -- we'll get it fixed ASAP.

**Comment by daviddurand** [comment]
This turns out to have been two things -- some very minor URL problems, and a really puzzling problem that took me a while to track down, since **I** was getting index blocks in my testing (on the live and test servers) but **you** were not getting them, as I was able to see.

It turns out that I was mistakenly using the (obsolete) `Collection Title Index` layout to generate my indexes, when your site, and all the other live sites actually use the plain old `Title Index` page.

The default layouts still support the  `Collection Title Index` because they contain a `Title Index` block. On your design that block had gotten blown away (probably during your changes to the master blocks). So the export was using the wrong template, but "correctly" applying that template to produce a blank page. Once I finally remembered that there are two page layouts, and that one of them is only in place to support a few old customer designs, I realized that the export was using the wrong one.

Apologies if the long explanation is boring, but I really wanted to explain why it looked like things were totally broken on your site, but not on any of my test sites. And my first two ideas were actually way off-base. Please work this over as soon as you can, and let me know if there's anything else.

**Comment by orangedrink** [comment]
Let me know when you get to fixing the links.

**Comment by daviddurand** [comment]
I think you misunderstood me -- all should be working, and it seemed to to me.  Checking again, I think I may see a link problem with the index links from static pages (which don't get their own indexes, as they don't have content)...

**Comment by orangedrink** [comment]
OK. Let me know when those are fixed.
