### ISSUE TITLE
Error "No signature of method getName matches the arguments"

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#91]
On handouts.sde.com we're seeing the error "No signature of method getName matches the arguments" instead of a listing of conferences the user has been tagged with.

To reproduce log in as kczubernat@sbcsc.k12.in.us with password 123

This is priority one right now. Thanks.

**Comment by daviddurand** [comment]
Fixed.

Sorry, the custom block got broken by the backend changes.

I'll check the Amia custom login block as well.

Ironically, I was looking into the log symptoms of this when I stopped for the static site stuff...

**Comment by orangedrink** [comment]
Thank you David!

**Comment by orangedrink** [comment]
SDE is asking if it would be possible to fork the code for the SDE site to prevent any problems like this in the future. Is that a possibility?

**Comment by daviddurand** [comment]
That solution is not in the cards, unless they want to pay a bunch extra in hosting costs. I agree that we've seen the maintenance downside of the "special block" that we created for SDE, and we should look at approaches to replace it with something less "special" that can be part of the normal testing process.

I see two ways that make sense: one would be for you to use the JSon stuff to do the special processing on the client side -- you could use the user login information to fetch the titles and URLs of their sessions quite quickly, as we know. That's an approach that we didn't have available when we created the site.

Another approach would be for me to extend the list block to include a function that works like the SDE block does. That will definitely take some time to schedule at this end, because it will have to be after the new reader, for instance, but I a agree that this should not be a problem that we have to continue to worry about.

The new stuff that went live today also includes another round of significant performance improvements in site rendering. I  was just testing on AMIA's super-huge page at:
http://proceedings.amia.org/2011/
Once it's been requested once (which warms the cache), it is delivered in around 2.3 seconds. The best we did with a warm cache last week was 8-10 seconds. With a cold cache the whole thing would take 14-30 seconds. Now even on a cold access it doesn't seem to take more than 14 seconds, and sometimes less.

I left a little testing comment at the bottom of the html, so I can see that the new cache saves 13,543 operations on that one page -- and there's still a bit more to come.
