### ISSUE TITLE
Freemarker template exception rendering page list blocks

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#95]
http://operations-namic2012.conferencespot.org/

None of the collections are showing up. The following is the only thing that shows up when trying to reach a collection:
Method public java.lang.Boolean com.cubchicken.layout.model.PageBlockSlotted.hasSlotChild(int) threw an exception when invoked on com.cubchicken.plugin.base.model.PageBlockStackedRows@4eb1f25

The same error message shows up on the home page and the footer.

Please let us know if there is something that we have setup incorrectly.

**Comment by daviddurand** [comment]
A performance improvement to database access (capable of delivering some pages 5 times faster than previously) triggered a bug in Hibernate, which was generating incorrect SQL statements. This would only occur when rendering pages where a list block was completely empty. Hibernate generated bad SQL when asked to fetch all database information for an empty list of objects.

This explains why it didn't show up in testing, or indeed on almost all in-production sites, as almost all list blocks on pages are not empty. While the primary error affected only empty lists on a page, once there was any SQL error, the transaction would be aborted, and later database operations would fail, potentially leading to further display problems, depending on the layout of the page.

**Comment by ghost** [comment]
So the bug has been fixed, or do we need to do more than just hide list blocks that are not being used in our standard "small" site so that we can get the speed improvements?

**Comment by daviddurand** [comment]
The bug is fixed, and won't recur. You don't have to make any changes. There's nothing wrong with empty list blocks, it's just something rare that we didn't cover in the testing, and it happened to interact badly with the hibernate bug on empty requests to the database. The modified performance fix will be in place tomorrow.

Sorry for any confusion. I wasn't telling you about something to watch out for, I just wanted to get a clear explanation of what happened into the problem log, for future use in testing, etc.
