### ISSUE TITLE
Can't move content blocks from workbench to design if they are in a stacked block.

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#97]
To reproduce place a stacked block in the workbench and add a block to one of it's slots. Now try to move this block into the layout. I'm seeing the target slot turn green and a short display of the loading graphic but I'm not able to actually move the block.

Let me know if you have any questions.

**Comment by daviddurand** [comment]
I think this may be a javascript bug, because you are not supposed to be able to change blocks in the workbench in any way. So the green lighting up when you try to drag something into a workbench slot is the error, not the failure of the block to stay there.

Similarly, the client is letting you thing that you can drag a block out from a stacked block in the workbench and drop it into the layout, when that operation is also not supposed to be legal.

I'm not sure that I am testing exactly the same thing you describe, as I get an error immediately when I try to add a block to a stacked block in the workbench.

I don't get an error when I try to drag a block out a stacked block that is in the workbench, but it does not move if I drop it in the layout. Sadly, the bug in this is that the attempt should also generate an error, although it doesn't today.

Basically if you want to edit a block, you've got to make a spare slot for it in the page layout, or use one of the obsolete layouts like "User Personalization" as a place to park the blocks while you work on them.

Let me know if I've misunderstood the exact events that constitute the problem, as I'm not completely sure I have it right.

Unfortunately, the difference between the workbench and other places you can put blocks is something that was designed into the system long ago, and that can be worked around with temporary slots in the layout -- Since it was never planned to be a place to edit blocks, we are more likely to add the missing error messages than to enhance the layout editor to work this way.

I will try to take a quick look at it, though, when I can get a chance. What I remember is that it's not actually at all easy to do because the workbench stays put between different layouts, which means that the database situation is totally different.

**Comment by orangedrink** [comment]
"Similarly, the client is letting you thing that you can drag a block out from a stacked block in the workbench and drop it into the layout, when that operation is also not supposed to be legal."

"I don't get an error when I try to drag a block out a stacked block that is in the workbench, but it does not move if I drop it in the layout. Sadly, the bug in this is that the attempt should also generate an error, although it doesn't today"

This is what I was trying to describe. I'm sure that we were able to work this way in the past. 

Thanks

**Comment by daviddurand** [comment]
I remember being frustrated at this particular restriction many times, and never removed it to my knowledge. I will check if there is an easy way to make this happen, but given that it's not supposed to work, I can't make any guarantees.
