### ISSUE TITLE
Full Screen Issue

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#99]
http://s64705085-preview.tizrapublisher.com/erisa-outline-book-chapter-2/1

On the title content page, clicking the full screen button opens the PDF in full screen without any controls.
This is only happening to us in the staging site, but need to find out what is going on and get it fixed before we publish anything live. Also, we can not publish it because the customer needs to approve changes.

**Comment by ghost** [comment]
Any word on this?

**Comment by daviddurand** [comment]
The block you are using does not do what you think it does. You're using the "full page" block which is not part of our standard designs for years now -- in fact, I'd forgotten that it even existed. It's not the same as the standard zoom link: what it does is to link to the PDF or JPG image of a page with no HTML.

The Zoomed mode used on all our standard designs and your other sites is enabled by the zoom link, which is automatically generated on every page as part of the page content block.

If you want to radically move the placement of the HTML link for the zoom mode, you could need to use an HTML block to put equivalent markup in another place, but I would prefer a javascript or CSS-based solution as just copying this kind of reader markup could leave you vulnerable to breakage due to any future markup changes we may make as the reader evolves. And there is a lot happening on that front right now.

**Comment by ghost** [comment]
Thanks for the help

**Comment by ghost** [comment]
Would it make sense to not have them automatically created and just let them be blocks that can be added to the page?

**Comment by daviddurand** [comment]
yes it would, but given that it's pretty easy to accomodate in a standard design, it's a low-priority item, and probably will remain so, awaiting a more complete approach to revamping the site design tools.
